### PR TITLE
feat: Update Pull Request Template for AVM Module

### PR DESCRIPTION
**Pull request by ChrisSidebotham**
## Pipeline Reference

Update to the Pull Request Template to direct changes to Azure Verified Modules

| Pipeline |
| - |
| N/A |

## Type of Change

- [x] Update to CI Environment or utlities (Non-module effecting changes)
- [ ] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [ ] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [ ] I have run `Set-AVMModule` locally to generate the supporting module files.
- [ ] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Comment by ChrisSidebotham** [comment]
@eriqua @AlexanderSehr @jtracey93  - Topic for discussion, blended this from current template in CARML and AVM

**Review by AlexanderSehr — DISMISSED** [review]

**Comment by AlexanderSehr** [comment]
Would be happy to approve this sooner than later and improve if need be

**Review by eriqua — DISMISSED** [review]
:ok:

**Comment by eriqua** [comment]
> Would be happy to approve this sooner than later and improve if need be

Agree, let's have

**Comment by ChrisSidebotham** [comment]
Waiting for prettier to work locally...

**Review by AlexanderSehr — APPROVED** [review]

**Pull request merged**
