### PR TITLE
feat: Container App added Sticky Session Afinity options

### PR DESCRIPTION
**Pull request by MichielVanHerreweghe**
## Description
Added the option to enable session affinity on the container app

## Pipeline Reference

| Pipeline |
| -------- |
| [avm.res.app.container-app](https://github.com/MichielVanHerreweghe/bicep-registry-modules/actions/workflows/avm.res.app.container-app.yml) |

## Type of Change

- [ ] Update to CI Environment or utlities (Non-module effecting changes)
- [x] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [x] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [ ] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Comment by MichielVanHerreweghe** [comment]
> @MichielVanHerreweghe please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Review by oZakari — APPROVED** [review]
LGTM, thank you @MichielVanHerreweghe! Just need someone from @Azure/avm-core-team to approve and we should be good. 👍🏼

**Comment by AlexanderSehr** [comment]
> LGTM, thank you @MichielVanHerreweghe! Just need someone from @Azure/avm-core-team to approve and we should be good. 👍🏼

Hey @oZakari actually you don't. That's the point of ownership 😉

**Comment by oZakari** [comment]
Thanks for the clarification @AlexanderSehr

**Comment by AlexanderSehr** [comment]
Please note, version `0.3.0` was just published

**Pull request merged**
