### PR TITLE
feat:   add securityContext to containerType for `avm/res/container-instance/container-group`

### LINKED ISSUE #1514: [AVM Module Issue]: securityContext not configurable for Container Instances
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/container-instance/container-group

### (Optional) Module Name if not listed above

_No response_

### (Optional) Module Version

0.1.0

### Description

The securityContext is not included in the type containerType.

I have a use case where I need to configure the capabilities for a container, and this is currently not possible.

I would be happy to create a PR for it.

### (Optional) Correlation Id

_No response_

### PR DESCRIPTION
**Pull request by mischavandenburg**
## Description

This adds the securityContext to the containerType. This makes it possible to configure capabilities, privilege escalation etc. 

Fixes #1514

## Pipeline Reference

| Pipeline |
| -------- |
|          |

I have some Service Principal trouble fixing the last step but the templates lint and deploy just fine:

image

## Type of Change

- [ ] Update to CI Environment or utlities (Non-module effecting changes)
- [x] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [x] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [x] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Comment by AlexanderSehr** [comment]
Hey @mischavandenburg,

just a note on the pipeline. The last step is only not working because the workflow assumes a run in the `main` branch happens only if you also want to publish. And because you cannot technically publish directly to the Public Registry, the login fails ;)

A colleague is currently working on adjusting this logic to skip the action if it's not run in upstream BRM in the first place, hence skip the failing login & the eventual `bicep publish`.

cc: @eriqua

**Comment by mischavandenburg** [comment]
@AlexanderSehr 

Thank you for the kind words! If this PR gets merged it would be my first proper contribution to Microsoft Open Source and I'm pretty excited :) 

 And you explanation of the pipeline, that was very kind of you.

**Comment by AlexanderSehr** [comment]
> @AlexanderSehr
> 
> Thank you for the kind words! If this PR gets merged it would be my first proper contribution to Microsoft Open Source and I'm pretty excited :)
> 
> And you explanation of the pipeline, that was very kind of you.

Looking forward to it. We just need the module's owner @JPEasier to take a look 💪

**Review by JPEasier — APPROVED** [review]

**Comment by AlexanderSehr** [comment]
off we go. Thanks @JPEasier and thank you @mischavandenburg 💪

**Comment by JPEasier** [comment]
Hi @mischavandenburg, 
thanks for your great contribution  👍  nice work! 🚀

**Comment by mischavandenburg** [comment]
Yay, it got merged! Happy to contribute, hope to do more in the time to come! Thanks @AlexanderSehr & @JPEasier

**Pull request merged**
