### PR TITLE
feat: Add the creation of 'Microsoft.Portal/dashboards' in Insights Module - `avm/res/insights/component`

### LINKED ISSUE #1130: [AVM Module Issue]: Application Insight Module should add the creation of 'Microsoft.Portal/dashboards'
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/insights/component

### (Optional) Module Name if not listed above

avm/res/insights/component

### (Optional) Module Version

_No response_

### Description

Please add the creation of `Microsoft.Portal/dashboards` and the output `applicationInsights.properties.ConnectionString`.
For example (azd): 
https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/monitor/applicationinsights.bicep#L19
https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/monitor/applicationinsights.bicep#L28

CC: @jongio

### (Optional) Correlation Id

_No response_

### PR DESCRIPTION
**Pull request by zedy-wj**
## Description

Fixes #1130 

## Pipeline Reference

| Pipeline |
| -------- |
[avm.res.insights.component](https://github.com/zedy-wj/bicep-registry-modules/actions/workflows/avm.res.insights.component.yml)

## Type of Change

- [ ] Update to CI Environment or utlities (Non-module effecting changes)
- [ x] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [ ] Update to documentation

## Checklist

- [ x] I'm sure there are no other open Pull Requests for the same update/change
- [ x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [ x] My corresponding pipelines / checks run clean and green without any errors or warnings

@jongio - for notification.

### CODE REVIEW

**Comment by AlexanderSehr** [comment]
Hey @zedy-wj,
thank you for the contribution. From where I'm standing (and considering the AVM specs) this needs some updates. Either
- The module is updated as is. That means, instead of adding the new resource as a child-module it shoud instead be a nested template in a `/modules/` subfolder like [here](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/compute/virtual-machine/modules) for the VM NIC & backup (as it is no child of `Microsoft.Insights/components` in the API sense), OR
- It should be a Pattern module that uses the Insights module as a nested resource and build the dahsboard around it.

What it qualifies for is subject to debate as the [spec](https://azure.github.io/Azure-Verified-Modules/specs/shared/module-classifications/#:~:text=They%20MAY%20include%20related%20resources%2C%20e.g.%20VM%20contains%20disk%20%26%20NIC.%20Focus%20should%20be%20on%20customer%20experience.%20A%20customer%20would%20expect%20that%20a%20VM%20module%20would%20include%20all%20required%20resources%20to%20provision%20a%20VM.) leaves a bit of wiggle room and it comes down to 
- how closely dashboards & app insights are correlated and 
- how common the use case is to deploy the 2 together

As this is not an easy answer, I'd also as the other maintainers @jtracey93, @eriqua, @ChrisSidebotham and of course the module owner @krbar to share your thoughts.

**Comment by jtracey93** [comment]
thanks for the PR. 

I think this feels like a new pattern module to me. As the dashboards could be a resource module own their own, and should be ideally. Then can be wrapped in many pattern modules

**Comment by jongio** [comment]
1. dashboard should be independent module
2. it could be included in a pattern module in the future


for now, let's get the dashboard module created if not there yet

**Comment by krbar** [comment]
Module proposal for the Dashboard module: https://github.com/Azure/Azure-Verified-Modules/issues/980

**Comment by eriqua** [comment]
Thanks @zedy-wj for raising this PR and triggering this discussion.

> 1. dashboard should be independent module
> 2. it could be included in a pattern module in the future
> 
> for now, let's get the dashboard module created if not there yet

+1 on the above. 
Create a new resource module for dashboard and discuss if adding a pattern module in the future. 
A pattern module would make sense if we think the integration can be reusable. If so +1 for the pattern as well. If not, I'd rather keep it covered by e2e deployment examples only.

**Comment by matebarabas** [comment]
Requires approved module proposal and prior publication to the MAR manifest. Do not merge, until both are confirmed here.

**Comment by eriqua** [comment]
Sorry if I missed it: what's the plan for this PR?
Is #2016 replacing it?

**Comment by zedy-wj** [comment]
> Sorry if I missed it: what's the plan for this PR? Is #2016 replacing it?

@eriqua - Currently https://github.com/Azure/bicep-registry-modules/pull/2016 is dealing with the creation of the dashboard module, this PR did not develop the dashboard as an independent module. We will close this PR and move the plan to fix #1130 to https://github.com/Azure/bicep-registry-modules/pull/2016.

@jongio - We will close this PR and move the plan to fix #1130 to https://github.com/Azure/bicep-registry-modules/pull/2016.

**Pull request closed without merging**
