### PR TITLE
feat: Add output 'fqdn' in MySQL Module - `avm/res/db-for-my-sql/flexible-server`

### LINKED ISSUE #2576: [AVM Module Issue]: MySQL Flexible Server Module should add the output `mysqlServer.properties.fullyQualifiedDomainName`
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/db-for-my-sql/flexible-server

### (Optional) Module Version

_No response_

### Description

Please add the output `mysqlServer.properties.fullyQualifiedDomainName`.

For example (azd):
https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/database/mysql/flexibleserver.bicep#L65

CC: @jongio

### (Optional) Correlation Id

_No response_

### PR DESCRIPTION
**Pull request by NanaXiong00**
## Description
Fixes https://github.com/Azure/bicep-registry-modules/issues/2576

## Pipeline Reference

| Pipeline |
| -------- |
|    [avm.res.db-for-my-sql.flexible-server](https://github.com/NanaXiong00/bicep-registry-modules/actions/workflows/avm.res.db-for-my-sql.flexible-server.yml)     |

The failure in the pipeline is due to the sku use `Burstable` tier in the test files, and the mode for `High Availability (HA)` is not supported for the `Burstable` pricing tier. And the `main` branch also had the same problem.

## Type of Change

- [ ] Update to CI Environment or utilities (Non-module affecting changes)
- [x] Azure Verified Module updates:
  - [ ] Bugfix containing backwards-compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [ ] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [ ] My corresponding pipelines / checks run clean and green without any errors or warnings

@jongio - for notification.

### CODE REVIEW

**Review by jtracey93 — DISMISSED** [review]
Hey @NanaXiong00,

Thanks for the PR, please can you ensure the WAF Reliability tests are passing, this is a requirement of the specifications for all AVM modules.

https://github.com/NanaXiong00/bicep-registry-modules/actions/runs/9772687652/attempts/1#summary-26977504642

The 2 failing PSRule tests are:
- https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.MySQL.MaintenanceWindow
- https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.MySQL.ZoneRedundantHA

Any issues please work with @hundredacres as the module owner, in the first instance to resolve these; but they should be pretty straight forward fixes 

Thanks

Jack

cc: @jongio

**Comment by NanaXiong00** [comment]
@hundredacres  WAF Reliability tests errors are not caused by current PR modification. Please help fix the above problems. PR permissions have been given.

**Comment by hundredacres** [comment]
These haven’t been easy to fix. Deploying a resource with the default settings fails with some opaque error that I’ve been trying to resolve. Once that’s fixed, the WAF test will also work.

Happy to pick up the PR when I can resolve the 2 failing tests.

Matt

**Comment by AlexanderSehr** [comment]
Hey together,
as the reliablity tests are enforced we unfortunately don't have a lot of wiggle room here. Either we fix them as part of this PR, or work on a fix seperately, merge it in first and then pull the changes into your branch @NanaXiong00.

Regarding the failing tests: As the `maintenanceWindow` does not require any user input (e.g., a refernece to another resource or similar), I guess we should consider setting a default value in the `main.bicep` file itself. For example
```bicep
param maintenanceWindow object = {
  customWindow: 'Enabled'
  dayOfWeek: 0
  startHour: 1
  startMinute: 0
}
```
Will run a test for it on the side

**Comment by NanaXiong00** [comment]
@hundredacres   According to [Alexander Sehr's suggestion,](https://github.com/Azure/bicep-registry-modules/pull/2606#issuecomment-2249609043) please help create a PR seperately to fix the WAF test error. After the PR is successfully merged, we will pull the latest code into the current branch.

**Comment by AlexanderSehr** [comment]
> @hundredacres According to [Alexander Sehr's suggestion,](https://github.com/Azure/bicep-registry-modules/pull/2606#issuecomment-2249609043) please help create a PR seperately to fix the WAF test error. After the PR is successfully merged, we will pull the latest code into the current branch.

Opening a PR yet won't help until the issue is resolved as we're effectively blocked now. But as soon as the issue is resolved we can work on the solution.

I tried a few different solutions as per https://github.com/Azure/bicep/discussions/10996
But as someone points out for this particular resource, no API version seemed to work. 

Here are my changes 
image

**Comment by hundredacres** [comment]
I have a link to an internal workitem/bug we can reference if there's a way to bypass a PS test.

**Comment by hundredacres** [comment]
@NanaXiong00 hoping to have the issues with the failing tests resolved soon so we can merge this PR. Thanks for your patience!

**Comment by NanaXiong00** [comment]
> @NanaXiong00 hoping to have the issues with the failing tests resolved soon so we can merge this PR. Thanks for your patience!

Thank you for your efforts in fixing the failed tests, and I'm looking forward to the merge of your PR  https://github.com/Azure/bicep-registry-modules/pull/2876.

**Comment by hundredacres** [comment]
@NanaXiong00 Pull the latest changes from main to your branch and resolve any local conflicts. You should then be able to kick off a pipeline run and get a green badge.

**Comment by NanaXiong00** [comment]
@hundredacres and @AlexanderSehr I have updated by commmits, pipeline run has passed, please review.

**Review by hundredacres — DISMISSED** [review]

**Comment by AlexanderSehr** [comment]
hm ... either it didn't work, or a new conflict arose. @NanaXiong00 could you double-check?
@hundredacres already approved, so I can keep an eye on it an approve the PR on his behalf once the conflict is resolved

**Comment by NanaXiong00** [comment]
> hm ... either it didn't work, or a new conflict arose. @NanaXiong00 could you double-check? @hundredacres already approved, so I can keep an eye on it an approve the PR on his behalf once the conflict is resolved

The conflict has been resolved, please review.

**Review by AlexanderSehr — APPROVED** [review]

**Pull request merged**
