### PR TITLE
fix: Front door web application firewall policy api version and types - `avm/res/network/front-door-web-application-firewall-policy`

### LINKED ISSUE #2988: [AVM Module Issue]: avm/res/network/front-door-web-application-firewall-policy old API version and missing types
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/network/front-door-web-application-firewall-policy

### (Optional) Module Version

_No response_

### Description

The API version for avm/res/network/front-door-web-application-firewall-policy is old, resulting in deployment error when configuring setting the javascriptChallengeExpirationInMinutes policy setting.

### (Optional) Correlation Id

_No response_

### PR DESCRIPTION
**Pull request by anderseide**
## Description

Changed api version number on the frontDoorWAFPolicy resource
Added types for managedRules and customRules to make the module more user friendly.

Fixes #2988

## Pipeline Reference

| Pipeline |
| -------- |
|    [avm.res.network.front-door-web-application-firewall-policy](https://github.com/anderseide/avm-bicep-registry-modules/actions/workflows/avm.res.network.front-door-web-application-firewall-policy.yml)      |

## Type of Change

- [ ] Update to CI Environment or utilities (Non-module affecting changes)
- [x] Azure Verified Module updates:
  - [x] Bugfix containing backwards-compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [x] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [ ] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Comment by eriqua** [comment]
@PaulJohnston88 would you have availability to review this contribution? Thanks!

**Comment by AlexanderSehr** [comment]
@anderseide, given the changes, please attach a pipeline badge of a successful pipeline run for this module & branch 💪

**Comment by anderseide** [comment]
@AlexanderSehr, build pipeline badge as requested: [avm.res.network.front-door-web-application-firewall-policy](https://github.com/anderseide/avm-bicep-registry-modules/actions/workflows/avm.res.network.front-door-web-application-firewall-policy.yml)

**Comment by AlexanderSehr** [comment]
> @AlexanderSehr, build pipeline badge as requested: [avm.res.network.front-door-web-application-firewall-policy](https://github.com/anderseide/avm-bicep-registry-modules/actions/workflows/avm.res.network.front-door-web-application-firewall-policy.yml)

Close @anderseide 😄 It's a badge for the `main` branch, while your implementation is in the `front-door-web-application-firewall-policy` branch. The correct badge would be:
[avm.res.network.front-door-web-application-firewall-policy](https://github.com/anderseide/avm-bicep-registry-modules/actions/workflows/avm.res.network.front-door-web-application-firewall-policy.yml)

Which unfortunately correct shows that the workflow did not run for the correct branch either. Small things, but important for the validation 💪

**Comment by anderseide** [comment]
> > @AlexanderSehr, build pipeline badge as requested: [avm.res.network.front-door-web-application-firewall-policy](https://github.com/anderseide/avm-bicep-registry-modules/actions/workflows/avm.res.network.front-door-web-application-firewall-policy.yml)
> 
> Close @anderseide 😄 It's a badge for the `main` branch, while your implementation is in the `front-door-web-application-firewall-policy` branch. The correct badge would be: [avm.res.network.front-door-web-application-firewall-policy](https://github.com/anderseide/avm-bicep-registry-modules/actions/workflows/avm.res.network.front-door-web-application-firewall-policy.yml)
> 
> Which unfortunately correct shows that the workflow did not run for the correct branch either. Small things, but important for the validation 💪

... let's try again [avm.res.network.front-door-web-application-firewall-policy](https://github.com/anderseide/avm-bicep-registry-modules/actions/workflows/avm.res.network.front-door-web-application-firewall-policy.yml)

**Comment by AlexanderSehr** [comment]
Looking great. Thanks @anderseide. @PaulJohnston88 please review as your capacity alows 💪

**Comment by ReneHezser** [comment]
@anderseide 
We have added examples for Bicep parameter files to the Readme. This has been applied to all published modules but needs to be done for PRs as well. Can you please run the Set-AVMModule utility as detailed [here](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/generate-bicep-module-files/). It is required for the validation pipeline to succeed and the contribution to be published.

Please reach out if any support is needed.

**Comment by anderseide** [comment]
> @anderseide We have added examples for Bicep parameter files to the Readme. This has been applied to all published modules but needs to be done for PRs as well. Can you please update your branch and run the Set-AVMModule utility as detailed [here](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/generate-bicep-module-files/). It is required for the validation pipeline to succeed and the contribution to be published.
> 
> Please reach out if any support is needed.

Updated the branch and ran Set-AVMModule

Updated build badge: [avm.res.network.front-door-web-application-firewall-policy](https://github.com/anderseide/avm-bicep-registry-modules/actions/workflows/avm.res.network.front-door-web-application-firewall-policy.yml)

**Review by AlexanderSehr — APPROVED** [review]
Given that the PR has been open for a while, I'll go ahead and approve and merge the PR on @PaulJohnston88's behalf. Please excuse the delay @anderseide. I'd have had a few minor suggestions, but did not want to delay your PR further. We can handle those later 😏

**Pull request merged**
