### PR TITLE
feat: Simplified System-Managed-Identity output

### PR DESCRIPTION
**Pull request by AlexanderSehr**
## Description

- Simplified System-Managed-Identity output
- Successful output (max):
  image
- Successful output (min):
  image

| Pipeline | 
| - |
| [avm.res.batch.batch-account](https://github.com/AlexanderSehr/bicep-registry-modules/actions/workflows/avm.res.batch.batch-account.yml) |

### CODE REVIEW

**Review by ilhaan — DISMISSED** [review]

**Review by ChrisSidebotham — CHANGES_REQUESTED** [review]
@AlexanderSehr - I would expect to see a version bump (Patch) with these changes?

**Comment by AlexanderSehr** [comment]
> @AlexanderSehr - I would expect to see a version bump (Patch) with these changes?

Hey @ChrisSidebotham if there'd be a feature change I'd agree. But the output is literally the same. The implementation is nothing more than a shorter version of the same code using the capabilities offered by Bicep

**Comment by ChrisSidebotham** [comment]
> Hey @ChrisSidebotham if there'd be a feature change I'd agree. But the output is literally the same. The implementation is nothing more than a shorter version of the same code using the capabilities offered by Bicep

Ok agreed. In the eyes of semantic versioning this change is completely internal and does not affect the modules interface or behaviour to an end user.

Reviewing again....

**Review by ChrisSidebotham — APPROVED** [review]
👌

**Pull request merged**
