### PR TITLE
fix: Add filtering to the budget.

### LINKED ISSUE #942: [AVM Module Issue]: Allow specification of filter for budget resource
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/consumption/budget

### (Optional) Module Name if not listed above

_No response_

### (Optional) Module Version

0.1.0

### Description

The budget resource is created with a filter of {}, which does not allow us to limit what the budget is associated with.  Ideally, I'd want the ability to specify a list of resourceGroups that then constructs a filter OR a filter when I want something custom.

I have this work already done, so will do a contribution - just filing the bug to associate it with.

### (Optional) Correlation Id

_No response_

### PR DESCRIPTION
**Pull request by adrianhall**
## Description
* Adds two new parameters to the main.bicep (`filter` and `resourceGroupFilter`) 
* Constructs a filter param for the budget based on the added parameters.
* Updates max e2e test to add the resourceGroupFilter option
* Updates README.md to add parameters and example.

> Edit @AlexanderSehr 
> | Pipeline |
> | - |
> | [avm.res.consumption.budget](https://github.com/adrianhall/bicep-registry-modules/actions/workflows/avm.res.consumption.budget.yml) |

Closes #942 

If you haven't already, read the full [contribution guide](https://github.com/Azure/bicep-registry-modules/blob/main/CONTRIBUTING.md). The guide may have changed since the last time you read it, so please double-check. Once you are done and ready to submit your PR, edit the PR description and run through the relevant checklist below.

Enable GitHub Workflows in your fork to enable auto-generation of assets with our [GitHub Action](/.github/workflows/push-auto-generate.yml).
To trigger GitHub Actions after auto-generation, [add a GitHub PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) as a secret in your forked repository called `PAT`.

## Updating an existing module

- [X] This is a bug fix:
  - [X] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
  - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
- [ ] I have run `brm validate` locally to verify the module files.
    **`brm validate` produces "Could not find modules folder", so cannot validate**
- [X] I have run deployment tests locally to ensure the module is deployable.
- [X] I have read the [Updating an existing module](https://github.com/Azure/bicep-registry-modules/blob/main/CONTRIBUTING.md#updating-an-existing-module) section in the contributing guide and updated the `version.json` file properly:
  - [ ] The PR contains backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`.
  - [X] The PR contains backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] The PR contains breaking changes, and I have bumped the MAJOR version in `version.json`.
- [X] I have updated the examples in README with the latest module version number.

### CODE REVIEW

**Comment by adrianhall** [comment]
Please note:  I have installed the dotnet tool, but running "brm validate" as suggested in contribution guide when in the `avm/res/consumption/budget` directory produces an error "Could not find the modules folder" - there isn't one, but it does mean that the brm tool does not work for AVM.

**Comment by AlexanderSehr** [comment]
> Please note: I have installed the dotnet tool, but running "brm validate" as suggested in contribution guide when in the `avm/res/consumption/budget` directory produces an error "Could not find the modules folder" - there isn't one, but it does mean that the brm tool does not work for AVM.

Hey @adrianhall, please ignore the BRM tool for your contribution. We're about to update the PR template. Please refer instead to the `avm/utilities/Set-AVMModule.ps1` script. 

cc: @matebarabas, @jtracey93 is that something we can get done this week?

**Comment by adrianhall** [comment]
Great - I have deployed both the filter and resourceGroupFilter version and done manual portal checks to make sure that it is doing the right thing.

**Comment by AlexanderSehr** [comment]
> Great - I have deployed both the filter and resourceGroupFilter version and done manual portal checks to make sure that it is doing the right thing.

Great thanks. One ask though - is there a chance you could have the module's pipeline running in your fork? At least the static tests, but even better the deployment tests? Just to minimize the chance on our end that something unexpected fails upon merge to main.

Also @segraef, please review ;)

**Comment by adrianhall** [comment]
Have triggered the consumption/budget workflow.  Not sure if you can see it here: https://github.com/adrianhall/bicep-registry-modules/actions/runs/7834618491

**Comment by AlexanderSehr** [comment]
> Have triggered the consumption/budget workflow. Not sure if you can see it here: https://github.com/adrianhall/bicep-registry-modules/actions/runs/7834618491
> 
> Edit: looks like I have to do more than normal to get azure deployments working (management group ID, etc.) so I'll get to this work this afternoon. As a contributor, it would be super helpful if there was a script that did all the setup work and just gave me the secrets to add to my github runner. As it is, it looks like I have to review several layers of docs just to figure out what to do and there are no docs on how to clean up afterwards.

Hey @adrianhall,
as the `bicep-registry-repository` is an open-source repository, any fork is automatically also open-source - and as a result the code and it's actions are visible (unless disabled). So in short - yes I can see it ;) I can even do you one better and added the pipeline badge to the original description on top of the PR.

image

Regarding the subscription, yes - there are instructions you can find [here](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/) as well. Just make sure, when you set a subscription up, that you run the 'avm.platform.toggle-avm-workflows' at least once to disable all workflows (as they otherwise run on a schedule once a week for testing purposes). It's recommended to only have the workflows enabled you actually want to test, if that makes sense 🚀

**Comment by adrianhall** [comment]
... and to follow up, obviously I am missing something.  All the deployment steps passed, but "Publishing" failed with a login error.  No idea why (I'm not giving you guys User Access Administrator - it's not something I have access to give you and that may be it).  However, the deployments now pass.

**Comment by AlexanderSehr** [comment]
> ... and to follow up, obviously I am missing something. All the deployment steps passed, but "Publishing" failed with a login error. No idea why (I'm not giving you guys User Access Administrator - it's not something I have access to give you and that may be it). However, the deployments now pass.

Nah, don't worry about the publishing. One of the maintainers is currently working on something that will refactor it a bit and ultimately we will make sure the publishing won't run from a fork as only the main repo is anyways allowed to push to the public registry. It is also only running from the main branch.

**Review by segraef — APPROVED** [review]
lgtm, thanks @adrianhall

**Pull request merged**
