### PR TITLE
feat: Use null value to evaluate behavior in publicNetworkAccess instead of empty string - `avm/res/cognitive-services/account`

### PR DESCRIPTION
**Pull request by jceval**
## Description

Request addresses the conditional statement logic for network access status based on the values of publicNetworkAccess and networkAcls. The expression ensures that if publicNetworkAccess is not empty, that value is used; otherwise, if networkAcls is not empty, the status is considered enabled; otherwise, it’s disabled. This aligns with the intended behavior of prioritizing publicNetworkAccess over networkAcls for determining network access status.

This change makes it so that an empty string passed to the module, will fail the deployment. If the value is not passed, then a null value will be interpreted as the default 'Disabled' behavior. This can only be overridden by explicitly passing 'Enabled'.

## Pipeline Reference

| Pipeline |
| -------- |
|     [avm.res.cognitive-services.account](https://github.com/jceval/bicep-registry-modules/actions/workflows/avm.res.cognitive-services.account.yml)    |

## Type of Change

- [ ] Update to CI Environment or utlities (Non-module effecting changes)
- [ ] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [x] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [ ] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [ ] I have run `Set-AVMModule` locally to generate the supporting module files.
- [ ] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Comment by ChrisSidebotham** [comment]
Hi @jceval, 

Thanks for your contribution!
Are you able to add a workflow status badge, more details see [here](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/#6-create-a-pull-request-to-the-public-bicep-registry).

**Comment by ilhaan** [comment]
@jceval In addition to the pipeline badge mentioned in the previous comment, you will need to run the `Set-AVMModule` utility in your local branch to generate the necessary ARM template file and README updates. More info [here](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/generate-bicep-module-files/).

**Comment by eriqua** [comment]
> @jceval In addition to the pipeline badge mentioned in the previous comment, you will need to run the `Set-AVMModule` utility in your local branch to generate the necessary ARM template file and README updates. More info [here](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/generate-bicep-module-files/).

@jceval would you have some time to drive this PR to closure?
Please reach out to the team if you need support on this one

**Comment by jceval** [comment]
> Hi @jceval,
> 
> Thanks for your contribution! Are you able to add a workflow status badge, more details see [here](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/#6-create-a-pull-request-to-the-public-bicep-registry).

@ChrisSidebotham I have added the mentioned badge. 
@ilhaan  I also updated the template and readme

**Comment by AlexanderSehr** [comment]
Impressive - this didn't work for the longest time due to a Bicep bug and could be fixed across a range of other modules that all needed the empty string as an interims allowed value :)

**Comment by ilhaan** [comment]
@jceval The pipeline badge needs to show a run for the `jceval:jaceval/cognitive-services-public-network-access` branch but I only see main branch runs on there.

**Comment by AlexanderSehr** [comment]
> @jceval The pipeline badge needs to show a run for the `jceval:jaceval/cognitive-services-public-network-access` branch but I only see main branch runs on there.

That's true. The pipeline badge would be this one:
[avm.res.cognitive-services.account](https://github.com/jceval/bicep-registry-modules/actions/workflows/avm.res.cognitive-services.account.yml)

Please note @jceval that you can select the branch you want to have the badge for in the window where you create it :)
image

Doesn't change the fact though that the workflow did 'apparently' not run for the branch 😄 It happens. I do see however @jceval that your workflow is slightly outdated in that it still contains the `cron` scheduler. A few weeks back we removed the automated scheduling to save you your hard earned Azure credits. I recommend to temporarily disable all actions, pull latest main (also into your branch), enable actions again and the run the (https://github.com/jceval/bicep-registry-modules/actions/workflows/platform.toggle-avm-workflows.yml)[https://github.com/jceval/bicep-registry-modules/actions/workflows/platform.toggle-avm-workflows.yml] workflow once to disable any unintended triggering of workflows through changes to files in `main`.

**Comment by jceval** [comment]
Got it working ! 😁

**Review by ilhaan — APPROVED** [review]

**Comment by ilhaan** [comment]
Thank you @jceval!

**Pull request merged**
