### PR TITLE
feat: initial module for Public IP Prefix

### LINKED ISSUE #336: [Module Proposal]: Public IP Prefixes
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

Public IP Prefixes - To provision Public IP Prefixes using Bicep module

### Module path

`network/public-ip-prefix`

### Describe the module

Public IP Prefixes - To provision Public IP Prefixes using Bicep module

https://learn.microsoft.com/en-us/azure/templates/microsoft.network/publicipprefixes?pivots=deployment-language-bicep

### PR DESCRIPTION
**Pull request by schandnani**
Fixes #336 

If you haven't already, read the full [contribution guide](https://github.com/Azure/bicep-registry-modules/blob/main/CONTRIBUTING.md). The guide may have changed since the last time you read it, so please double-check. Once you are done and ready to submit your PR, edit the PR description and run through the relevant checklist below.

Enable GitHub Worksflows in your fork to enable auto-generation of assets with our [GitHub Action](/.github/workflows/push-auto-generate.yml).
To trigger GitHub Actions after auto-generation, [add a GitHub PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) as a secret in your forked repository called `PAT`.

## Adding a new module

- [ ] A proposal has been submitted and approved.
- [x] I have included "Closes #{module_proposal_issue_number}" in the PR description.
- [x] I have run `brm validate` locally to verify the module files.
- [x] I have run deployment tests locally to ensure the module is deployable.

## Updating an existing module

- [ ] This is a bug fix:
  - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
  - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
- [ ] I have run `brm validate` locally to verify the module files.
- [ ] I have run deployment tests locally to ensure the module is deployable.
- [ ] I have read the [Updating an existing module](https://github.com/Azure/bicep-registry-modules/blob/main/CONTRIBUTING.md#updating-an-existing-module) section in the contributing guide and updated the `version.json` file properly:
  - [ ] The PR contains backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`.
  - [ ] The PR contains backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] The PR contains breaking changes, and I have bumped the MAJOR version in `version.json`.
- [ ] I have updated the examples in README with the latest module version number.

### CODE REVIEW

**Comment by shenglol** [comment]
Can you change the module name to a singular, i.e., `public-ip-prefix`?

**Comment by schandnani** [comment]
@shenglol changed the module name to public-ip-prefix.

**Comment by schandnani** [comment]
Hey @shenglol any update on the MCR?

**Comment by schandnani** [comment]
Any update on this please?

**Review by shenglol — APPROVED** [review]
:shipit:

**Pull request merged**
