### PR TITLE
feat: Create\Update User Defined Types with sensitive values to include @secure() decorator. - `avm/res/container-instance/container-group`

### LINKED ISSUE #1868: [AVM Module Issue]: container-instance/container-group doesnt allow for secure environmentVariables to be passed
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Security Bug

### Module Name

avm/res/container-instance/container-group

### (Optional) Module Version

_No response_

### Description

Current module doesn't allow for secure environmentVariables to be passed "securely".
This is an attribute of the containers object and therefore any environment variables passed will appear as plain text in the deployment.

Is there a way to decouple that attribute from the containers object as to pass it in a different parameter that can have the `secure()` decorator and then marry it back up with the object in the module?

I have done this for my specific requirement but have therefore not allowed for containers to be an array (as i only need to deploy 1).
Eg:
Module file: 
image
image

Calling bicep:
image

Of course this example above is not the best approach for this AVM module as it is limiting but happy to assist in modifying the module once approved approach is decided.

Thanks

### (Optional) Correlation Id

_No response_

### PR DESCRIPTION
**Pull request by rodney-almeida**
## Description
Update containerType (user defined type) to set environmentVariables.secureValue to be of type secureString.
Followed the same logic and created the user defined type for imageRegistryCredentials (imageRegistryCredentialType) as it also has a password attribute.

Fixes #1868
Closes #1868
-->

## Pipeline Reference

| Pipeline |
| -------- |
[avm.res.container-instance.container-group](https://github.com/rodney-almeida/bicep-registry-modules/actions/workflows/avm.res.container-instance.container-group.yml)

## Type of Change

- [ ] Update to CI Environment or utlities (Non-module effecting changes)
- [ ] Azure Verified Module updates:
  - [X] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [X] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [ ] Update to documentation

## Checklist

- [X] I'm sure there are no other open Pull Requests for the same update/change
- [X] I have run `Set-AVMModule` locally to generate the supporting module files.
- [X] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Comment by AlexanderSehr** [comment]
Looks great @rodney-almeida, 
thank you for your contribution, pipeline-badge and all. @JPEasier please take a look when you have a moment :)

**Review by JPEasier — APPROVED** [review]

**Comment by JPEasier** [comment]
Thank You @rodney-almeida for your contribution, looks greate! 🚀

**Comment by rodney-almeida** [comment]
@JPEasier, looks like the pipeline failed to delete some resources when running the tests after the merge. As a result the new version hasn't been published. You able to kick off the pipeline again?

**Comment by AlexanderSehr** [comment]
> @JPEasier, looks like the pipeline failed to delete some resources when running the tests after the merge. As a result the new version hasn't been published. You able to kick off the pipeline again?

Hey @rodney-almeida & @JPEasier, just fyi, I saw this and already tried troubleshooting. The workflow is facing the same issue I was in the Portal. The service is borderline refusing to be removed. This happend with 2 or 3 other services in the past were we ended up needing support questions to get them removed. I hope this won't be needed here, and I'll keep on trying. Once the service is removed, we can re-run only the 'failed jobs' of the failed pipeline. 
**Fyi** @JPEasier, we should not start a new workflow run for **main** as this would not tigger the publishing (as there would be no diff).

**Comment by rodney-almeida** [comment]
@AlexanderSehr, any luck with the support ticket?
Keen to stop using my local bandaid version and get back to using the AVM module :)
Thanks

**Comment by AlexanderSehr** [comment]
> @AlexanderSehr, any luck with the support ticket? Keen to stop using my local bandaid version and get back to using the AVM module :) Thanks

Hey @rodney-almeida, the ticket was acknoledged but is yet to be resolved. I'll keep you posted 💪

**Comment by rodney-almeida** [comment]
> > @AlexanderSehr, any luck with the support ticket? Keen to stop using my local bandaid version and get back to using the AVM module :) Thanks
> 
> Hey @rodney-almeida, the ticket was acknoledged but is yet to be resolved. I'll keep you posted 💪

Any news?
Thanks

**Comment by AlexanderSehr** [comment]
> > > @AlexanderSehr, any luck with the support ticket? Keen to stop using my local bandaid version and get back to using the AVM module :) Thanks
> > 
> > 
> > Hey @rodney-almeida, the ticket was acknoledged but is yet to be resolved. I'll keep you posted 💪
> 
> Any news? Thanks

Not yet, no. Just yesterday I was asked by the ticket owner to try and run the removal via PowerShell and the Azure CLI, which, as expected, did not help.

**Comment by rodney-almeida** [comment]
@AlexanderSehr any luck yet?

**Comment by AlexanderSehr** [comment]
> @AlexanderSehr any luck yet?

Yes and no. I did get some feedback that the issue is connected to the deployed MSI (and the order of removal) which is why I opened the PR #2180. 
I have to port the PR over to my fork though to test there, as the AVM test subscription still has the faulty container-group deployed, and I cannot deploy over it. Support is still working on that part.

Will let you know once I was able to validate that the suggested update to the removal logic helped.

**Comment by rodney-almeida** [comment]
> > @AlexanderSehr any luck yet?
> 
> Yes and no. I did get some feedback that the issue is connected to the deployed MSI (and the order of removal) which is why I opened the PR #2180. I have to port the PR over to my fork though to test there, as the AVM test subscription still has the faulty container-group deployed, and I cannot deploy over it. Support is still working on that part.
> 
> Will let you know once I was able to validate that the suggested update to the removal logic helped.

Sorry to bug @AlexanderSehr but have we had any progress on this?

**Comment by AlexanderSehr** [comment]
> > > @AlexanderSehr any luck yet?
> > 
> > 
> > Yes and no. I did get some feedback that the issue is connected to the deployed MSI (and the order of removal) which is why I opened the PR #2180. I have to port the PR over to my fork though to test there, as the AVM test subscription still has the faulty container-group deployed, and I cannot deploy over it. Support is still working on that part.
> > Will let you know once I was able to validate that the suggested update to the removal logic helped.
> 
> Sorry to bug @AlexanderSehr but have we had any progress on this?

Hey @rodney-almeida, 
nothing to be satsified with, no.

The PR with the presumed change got merged some time ago: https://github.com/Azure/bicep-registry-modules/pull/2202

But the last response I got from support (from the 9th) was that they're waiting for the escelation in the back to proceed. So we're waiting, the middle-man is waiting, and we can just hope that to gears are turning somewhere. I'll ping the engineer again regardless.

**Comment by RodneyAlmeidaTEKenable** [comment]
@AlexanderSehr, I know this is an old request but have we been able to get anywhere with this? I came across this today because I needed to use this module again and still have to revert to using my local copy as the version from this PR hasn't been published yet.

**Comment by AlexanderSehr** [comment]
> @AlexanderSehr, I know this is an old request but have we been able to get anywhere with this? I came across this today because I needed to use this module again and still have to revert to using my local copy as the version from this PR hasn't been published yet.

oh wow. Thanks for calling this out @RodneyAlmeidaTEKenable. The pipeline started working again quite a while ago but it seems as no change that influences the module's functionality was merged since, no new version was published. Let me give it a shot with a new PR.

**Pull request merged**
