### PR TITLE
fix: InvalidKeyRotationPolicy

### PR DESCRIPTION
**Pull request by marcingastol**
## Pipeline Reference

| Pipeline |
| -------- |
|     [avm.res.key-vault.vault](https://github.com/marcingastol/bicep-registry-modules/actions/workflows/avm.res.key-vault.vault.yml)    |

## Type of Change

- [ ] Update to CI Environment or utilities (Non-module affecting changes)
- [ X] Azure Verified Module updates:
  - [ ] Bugfix containing backwards-compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ X] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ X] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ X] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [ X] Update to documentation

## Checklist

- [ X] I'm sure there are no other open Pull Requests for the same update/change
- [ X] I have run `Set-AVMModule` locally to generate the supporting module files.
- [ X] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Comment by marcingastol** [comment]
@microsoft-github-policy-service agree

**Comment by fblix** [comment]
waiting for @marcingastol to up the version in the version.json before merging this one :)

**Comment by ReneHezser** [comment]
@marcingastol 
We have added examples for Bicep parameter files to the Readme. This has been applied to all published modules but needs to be done for PRs as well. Can you please run the Set-AVMModule utility as detailed [here](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/generate-bicep-module-files/). It is required for the validation pipeline to succeed and the contribution to be published.

Please reach out if any support is needed.

**Review by fblix — DISMISSED** [review]

**Comment by marcingastol** [comment]
> @marcingastol We have added examples for Bicep parameter files to the Readme. This has been applied to all published modules but needs to be done for PRs as well. Can you please update your branch and run the Set-AVMModule utility as detailed [here](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/generate-bicep-module-files/). It is required for the validation pipeline to succeed and the contribution to be published.
> 
> Please reach out if any support is needed.

Hello @ReneHezser, I did what you mentioned - run Set-AVMModule as described in docs, however no differerences in Readme files have been detected in my version. This is command I ran:

Set-AVMModule -ModuleFolderPath ".\bicep-registry-modules\avm\res\key-vault\vault" -Recurse -SkipBuild

**Comment by ReneHezser** [comment]
Hi @marcingastol 
I checked the files in your PR and you are fine. The changes you made, do not affect the Readme. 
Sorry about that. 
René

**Review by fblix — APPROVED** [review]

**Pull request merged**
