### PR TITLE
feat: Added UDTs for Azure Firewall Application, network and NAT rules - `avm/res/network/azure-firewall`

### PR DESCRIPTION
**Pull request by johnlokerse**
## Description

This pull request adds UDTs for Azure Firewall application, network, and NAT rules. Also, added an extra network rule for service tags in the `max` test. 

@hundredacres @AlexanderSehr We must be aware that the change itself is not breaking, but when existing rules are not written as the UDT expects it will break a deployment. See the image below (left is how it is now and right is what's new with the UDT). How do we handle this version wise?

image

## Pipeline Reference

| Pipeline |
| -------- |
| [avm.res.network.azure-firewall](https://github.com/johnlokerse/bicep-registry-modules/actions/workflows/avm.res.network.azure-firewall.yml) |

## Type of Change

- [ ] Update to CI Environment or utlities (Non-module effecting changes)
- [ ] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [x] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Comment by AlexanderSehr** [comment]
Hey @johnlokerse, if in doubt I'd rather consider it breaking. As we're not on version 1.* yet, I'd suggest to update the module's minor version. @hundredacres what's your take?

**Comment by johnlokerse** [comment]
> Hey @johnlokerse, if in doubt I'd rather consider it breaking. As we're not on version 1.* yet, I'd suggest to update the module's minor version. @hundredacres what's your take?

@hundredacres Do you have feedback on the PR? 😃

**Comment by AlexanderSehr** [comment]
> > Hey @johnlokerse, if in doubt I'd rather consider it breaking. As we're not on version 1.* yet, I'd suggest to update the module's minor version. @hundredacres what's your take?
> 
> @hundredacres Do you have feedback on the PR? 😃

Hey @johnlokerse, @hundredacres may be on an Easter break. Just added a tag to draw attention, but let's wait a while longer. Those darn public holidays 😄

**Comment by hundredacres** [comment]
@johnlokerse @AlexanderSehr I'm onboard with bumping the minor version to account for the addition of the UDT.

**Comment by johnlokerse** [comment]
Bumped version to `0.2`! 👍

**Comment by AlexanderSehr** [comment]
Hey @hundredacres, just a ping so that a notification is raised :)

**Review by hundredacres — APPROVED** [review]
Approved.

**Pull request merged**
