### PR TITLE
fix: Only use isHnsEnabled property when explicitly specified in `avm/res/storage/storage-account`

### LINKED ISSUE #1522: [Question/Feedback]: Ignore (unchanged) read-only properties in Bicep during deployment
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I'm using an AVM Bicep module to deploy a storage account that was created by a different language to deploy infrastructure.  I'm looking to migrate the infrastructure code to Bicep in combination with Azure deployment stacks to make our setup simpler and faster.

However, it seems like _because_ the resource already exists, it throws the following error:

```
Code: DeploymentFailed
Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.
Target: /subscriptions/xxxx/resourceGroups/rg-xxx/providers/Microsoft.Resources/deployments/xxx
Exception Details:      (AccountPropertyCannotBeUpdated) The property 'isHnsEnabled' was specified in the input, but it cannot be updated as it is read-only. For more information, see - https://aka.ms/storageaccountupdate
```

I've tried setting the property `enableHierarchicalNamespace` for the `storage-account` AVM to `null`, `false`, `true`, and I've left it out entirely as well. But it always results into the same error.

I expect this same issue will arise when deploying other resources as well. It would help me if I can either ignore (unchanged) fields, or import resources somehow such that Azure at least thinks it has deployed that resource before.

There's [an open issue](https://github.com/Azure/azure-rest-api-specs/issues/18441) which is somewhat related, but this is about the actual Bicep resource, whereas my issue is with the Bicep AVM.

### PR DESCRIPTION
**Pull request by bartcode**
## Description

Instead of always providing the `isHnsEnabled` property, only provide it when the `enableHierarchicalNamespace` parameter to the `storage-account` module is set to `true` or `false`. Otherwise, leave it out.

Important notes:
- I'm making the `enableHierarchicalNamespace` parameter a `bool?`. Please verify carefully whether I'm missing a scenario there which would lead to this being a breaking change.
- The `networkAclsType` was optional, but the param `networkAcls` got a default value. I removed the `?` in the definition of the `networkAclsType` in order to run `bicep build`. But I'm not sure this parameter should actually be nullable.

This closes #1522 .

## Pipeline Reference

| Pipeline |
| -------- |
|  [avm.res.storage.storage-account](https://github.com/bartcode/bicep-registry-modules/actions/workflows/avm.res.storage.storage-account.yml)  |

## Type of Change

- [ ] Update to CI Environment or utlities (Non-module effecting changes)
- [x] Azure Verified Module updates:
  - [x] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [x] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [ ] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [ ] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Comment by bartcode** [comment]
@microsoft-github-policy-service agree

**Comment by fblix** [comment]
@bartcode can you pull the latest changes from main and run the pipeline again? we had a bit of trouble the last week with a failing pipeline on main.

**Comment by bartcode** [comment]
@fblix , yes, I will. Will probably take another look tomorrow. I was actually waiting for #1508 to be merged first, but it seems like it's silent there now.

**Comment by fblix** [comment]
@bartcode I will try to work on #1508 tomorrow, so hopefully something happens there soon ;)

**Comment by bartcode** [comment]
@fblix , just found out PRs automatically close when there's no change. I removed my previous commit and then it closed. I'll create a new PR when the #1508 has been merged.

**Comment by bartcode** [comment]
@ChrisSidebotham , here you go: #2017 .

**Pull request closed without merging**
