### PR TITLE
feat: `avm/res/app/managed-environment` storage

### PR DESCRIPTION
**Pull request by arnaud-tincelin**
## Description

New feature: possibility to add storages (NFS or SMB) on a container apps environment.

## Pipeline Reference

| Pipeline |
| -------- |
| [avm.res.app.managed-environment](https://github.com/arnaud-tincelin/bicep-registry-modules/actions/workflows/avm.res.app.managed-environment.yml) |

## Type of Change

- [ ] Update to CI Environment or utilities (Non-module affecting changes)
- [ ] Azure Verified Module updates:
  - [ ] Bugfix containing backwards-compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [X] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [ ] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Comment by eriqua** [comment]
@hundredacres @arnoldna would you have some time to please review this PR?

**Comment by hundredacres** [comment]
@arnaud-tincelin do you have a pipeline badge you can add so we can confirm the changes are working in your branch?

**Comment by arnoldna** [comment]
> @hundredacres @arnoldna would you have some time to please review this PR?

Yes

**Comment by arnaud-tincelin** [comment]
@arnoldna @hundredacres any news about merging this?

**Comment by hundredacres** [comment]
@arnaud-tincelin Sorry for the delay in getting back to you. If you could remove the unused output from the dependancies file, we can merge this change in.

**Comment by arnaud-tincelin** [comment]
@hundredacres done

**Review by hundredacres — APPROVED** [review]
Approved.

**Pull request merged**
