### PR TITLE
fix: Update the name of the `aksAcrPull` module from hard-coded to a variable.

### PR DESCRIPTION
**Pull request by Menghua1**
## Description
Updated the name of the aksAcrPull module from hard-coded to a variable. To ensure that the resource names created for each deployment are unique.

## Pipeline Reference

| Pipeline |
| -------- |
|     [avm.ptn.azd.acr-container-app](https://github.com/Menghua1/bicep-registry-modules/actions/workflows/avm.ptn.azd.acr-container-app.yml)     |

## Type of Change

- [ ] Update to CI Environment or utilities (Non-module affecting changes)
- [x] Azure Verified Module updates:
  - [ ] Bugfix containing backwards-compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [ ] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings

@jongio for notification.

### CODE REVIEW

**Comment by Menghua1** [comment]
@AlexanderSehr Could you please review this PR?

**Comment by AlexanderSehr** [comment]
> @AlexanderSehr Could you please review this PR?

Hey @Menghua1,
now that the module is merged, @jongio, as the owner should ideally review the PRs (in alignment with the AVM specs). That's the idea behind 'scaling through the owners' 😉 
If @jongio does not have any capacity, we maintainers can of course try to help out. 💪

**Comment by Menghua1** [comment]
@jongio When updating [PR#3976](https://github.com/Azure/azure-dev/pull/3976), it was found that the name of the module `aksAcrPull` in `ptn/azd/acr-container-app` was hardcoded during the migration process. When this module was created multiple times at the same time, a conflict error occurred. So I opened this PR, please review it, thank you.

**Comment by v-xuto** [comment]
@jongio Could you hep review this PR? It blocks the progress of migration to avm.

**Review by jongio — APPROVED** [review]

**Comment by Menghua1** [comment]
@AlexanderSehr Could you please review and approve this PR?

**Comment by AlexanderSehr** [comment]
> @AlexanderSehr Could you please review this PR? If there is no issue, please approve it.

Hey @Menghua1, @jongio should have the permissions to merge the PR. I can merge it on his behalf - but usually would suggest against that as he may've had a reason I do not know. Will reach out

**Comment by v-xuto** [comment]
@jongio Could you help merge this PR? Thanks a lot.

**Pull request merged**
