### PR TITLE
fix: `avm/res/web/serverfarm` support for elasticScaleEnabled property

### LINKED ISSUE #2335: [AVM Module Issue]: Missing elasticScaleEnabled param
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/web/serverfarm

### (Optional) Module Version

_No response_

### Description

The module supports specifying `maximumElasticWorkerCount` property. 

There is no way to actually enable the Elastic Scale itself, which is specified using property `elasticScaleEnabled`

Please add support for this parameter in the module

### (Optional) Correlation Id

_No response_

### PR DESCRIPTION
**Pull request by pankajagrawal16**
## Description

Fixes #2335 

## Pipeline Reference

| Pipeline |
| -------- |
|     [avm.res.web.serverfarm](https://github.com/pankajagrawal16/bicep-registry-modules/actions/workflows/avm.res.web.serverfarm.yml)    |

## Type of Change

- [ ] Update to CI Environment or utilities (Non-module affecting changes)
- [x] Azure Verified Module updates:
  - [x] Bugfix containing backwards-compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [x] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [x] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Comment by ChrisSidebotham** [comment]
Hey @pankajagrawal16 

Thanks for your contribution. Are you able to run the 'Set-AVMModule` utility to update the documentation for the module?

Don't forget to add a workflow status badge, more details see [here](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/#6-create-a-pull-request-to-the-public-bicep-registry).

**Comment by ChrisSidebotham** [comment]
@tsc-buddy  to review when ready

**Comment by pankajagrawal16** [comment]
@ChrisSidebotham I will try and do those steps now

**Comment by pankajagrawal16** [comment]
@ChrisSidebotham I am not sure which badge do I need to put ? It looks like its running on Azure pipeline instead of github action which the docs guides to 
image

Can you confirm ?

I have run `Set-AVMModule` and docs are updated using it.

**Comment by tsc-buddy** [comment]
Hi @pankajagrawal16, Thanks for contributing. You should have the avm.res.web.serverfarm workflow under Actions in your fork. Run that against your branch and it should pass successfully upto the publishing step, where it will skip. Grab that badge from the pipeline run when done.

**Comment by pankajagrawal16** [comment]
@tsc-buddy Thanks for feedback, I know this is strange, but for some reason i do not see this action or be it any other action apart from this one 
image

Any thoughts on why it could be ? Even thought action is present https://github.com/pankajagrawal16/bicep-registry-modules/blob/fix-enable-automatic-scale-support/.github/workflows/avm.res.web.serverfarm.yml

Still does not shows up to run 🤔

**Comment by pankajagrawal16** [comment]
@tsc-buddy Please let me know how to proceed further on this ?

**Comment by pankajagrawal16** [comment]
ok @tsc-buddy I finally managed to figure it out. 

It was because I never pushed anything to my forked main and thats why the action was never triggerred and did not show up in actions tab. Had a make a push to my forked main for it to show up and then i can make a run against branch.

Also when I ran the workflow, it failed coz of missing azure credentials at deployment step which makes sense to me since I dont have anything configured.

Anyways I have updated the PR with the badge. Also will be nice to put this somewhere as a note in contributor guide this gotcha. 

Let me know if anything else is needed. Will be great to get this change in the module.

**Comment by tsc-buddy** [comment]
Good stuff. Thanks @pankajagrawal16 - If you have an Azure subscription to set up the rest of CI with by following these steps, please do so the test deployments check. 

https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/#3-configure-your-ci-environment

**Comment by pankajagrawal16** [comment]
@tsc-buddy Ok did that and workflow is now green at deployment stage too. Hopefully its good to go now?

**Comment by pankajagrawal16** [comment]
Btw, love the automation in the project in general. Definitely in the rite direction

**Review by tsc-buddy — APPROVED** [review]

**Comment by tsc-buddy** [comment]
Thanks @pankajagrawal16 - appreciate the support

**Pull request merged**
