### PR TITLE
fix: service bus authorization rules default value fix

### LINKED ISSUE #1694: [Bug Report]:  AuthRule bicep referenced in queue bicep does not retrieve rights
### Describe the bug

We've recently started developing biceps that wrap the resourcemodules located in this repository. Passing a value in authorizationRules or using the default value for authorizationRules in queue/deploy.bicep gives the following error 
```json
{
    "status": "Failed",
    "error": {
        "code": "EmptyAccessRights",
        "message": "Empty access rights. Supported claims count 3"
    }
}
```
We can also see this in the deployment itself
image

Setting authorizationRules to an empty array works as this makes sure we avoid calling the sub-bicep for authorizationRules. 

Error occurs in rights-parameter in this bicep 
image

### To reproduce

Deploy a queue with with default authorizationRules

### Code snippet

```Bicep
This does not work as default parameter is used

@description('Optional. Authorization Rules for the Service Bus Queue.')
var authorizationRules  = [
  
]

module queue 'br:***.azurecr.io/resourcemodules/microsoft.servicebus/namespaces/queues:2023-02-16' = {
  name: '${queueName}-namespaces.queue-${deploymentSuffix}'
  params: {
    name:queueName
    namespaceName:serviceBusName
    duplicateDetectionHistoryTimeWindow: 'PT10M'
    enableBatchedOperations:             enableBatchedOperations
    enableExpress:                       enableExpress
    enablePartitioning:                  enablePartitioning
    maxSizeInMegabytes:                  maxSizeInMegabytes
    requiresDuplicateDetection:          requiresDuplicateDetection
    defaultMessageTimeToLive:            defaultMessageTimeToLive
    maxDeliveryCount:                    maxDeliveryCount
   // authorizationRules:authorizationRules

    
  }
}

This works as no rule is setup
@description('Optional. Authorization Rules for the Service Bus Queue.')
var authorizationRules  = [
  
]

module queue 'br:***.azurecr.io/resourcemodules/microsoft.servicebus/namespaces/queues:2023-02-16' = {
  name: '${queueName}-namespaces.queue-${deploymentSuffix}'
  params: {
    name:queueName
    namespaceName:serviceBusName
    duplicateDetectionHistoryTimeWindow: 'PT10M'
    enableBatchedOperations:             enableBatchedOperations
    enableExpress:                       enableExpress
    enablePartitioning:                  enablePartitioning
    maxSizeInMegabytes:                  maxSizeInMegabytes
    requiresDuplicateDetection:          requiresDuplicateDetection
    defaultMessageTimeToLive:            defaultMessageTimeToLive
    maxDeliveryCount:                    maxDeliveryCount
    authorizationRules:authorizationRules

    
  }
}
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by ChrisSidebotham**
## Description

Closes #1694 

## Pipeline Reference

| Pipeline |
| -------- |
|      [avm.res.service-bus.namespace](https://github.com/ChrisSidebotham/bicep-registry-modules/actions/workflows/avm.res.service-bus.namespace.yml)    |

## Type of Change

- [ ] Update to CI Environment or utlities (Non-module effecting changes)
- [x] Azure Verified Module updates:
  - [x] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [x] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [x] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Review by AlexanderSehr — CHANGES_REQUESTED** [review]
I'd argue this is a breaking change justifying an update of the `version.json` file's minor. Would you agree @ChrisSidebotham?

**Comment by ChrisSidebotham** [comment]
Version file bumped @AlexanderSehr

**Review by AlexanderSehr — APPROVED** [review]

**Comment by AlexanderSehr** [comment]
Approved @ChrisSidebotham, merge at will

**Comment by nmcguffey** [comment]
Nice work.  This fix helped me with my service bus deployments.  I was also able to apply this same change for this parameter in the topic module by updating service-bus/namespace/topic/main.bicep in my own repo.  I suggest applying this same change for topics otherwise we run into the same issue.

@description('Optional. Authorization Rules for the Service Bus Queue.')
param authorizationRules array = []

**Comment by AlexanderSehr** [comment]
> o able to apply this same change for this parameter in the topic module by updating service-bus/namespace/topic/main.bicep in my own repo. I suggest applying this same change for topics otherwise we run into the same issue.

Hey @ChrisSidebotham, please note :)
@nmcguffey, could you create an issue for tracking?

**Comment by nmcguffey** [comment]
> > o able to apply this same change for this parameter in the topic module by updating service-bus/namespace/topic/main.bicep in my own repo. I suggest applying this same change for topics otherwise we run into the same issue.
> 
> Hey @ChrisSidebotham, please note :) @nmcguffey, could you create an issue for tracking?

Thanks.  I created issue https://github.com/Azure/bicep-registry-modules/issues/2908

**Pull request merged**
