### PR TITLE
fix: Support for cilium network policy

### PR DESCRIPTION
**Pull request by cv-gh**
**Supporting cilium network policy in AKS**

cilium data plane requires cilium network policy. when specifying azure policy for cilium we get an error - CiliumDataplaneRequiresNetworkPolicyCilium

Configuration 
networkPolicy: 'azure'
networkPlugin: 'azure'
networkDataplane: 'cilium'

Detailed Error 
"message":"{\r\n  \"code\": \"BadRequest\",\r\n  \"details\": null,\r\n  \"message\": \"Cilium dataplane requires network policy cilium.\",\r\n  \"subcode\": \"CiliumDataplaneRequiresNetworkPolicyCilium\",\r\n  \"target\": \"networkProfile.networkPolicy\"\r\n}"}]}]

## Pipeline Reference

| Pipeline |
| -------- |
[avm.res.container-service.managed-cluster](https://github.com/cv-gh/bicep-registry-modules/actions/workflows/avm.res.container-service.managed-cluster.yml)

## Type of Change

- [ ] Update to CI Environment or utilities (Non-module affecting changes)
- [ ] Azure Verified Module updates:
  - [ ] Bugfix containing backwards-compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [x ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [ ] Update to documentation

## Checklist

- [x ] I'm sure there are no other open Pull Requests for the same update/change
- [ ] I have run `Set-AVMModule` locally to generate the supporting module files.
- [ ] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Comment by PixelRobots** [comment]
I think as you can only use cilium network policies with cilium dataplane and overlay it might be wise to also set this. 

```yaml
    networkPolicy: networkDataplane == 'cilium' ? 'cilium' : networkPolicy
    networkPluginMode: networkDataplane == 'cilium' ? 'overlay' : networkPluginMode
```

**Comment by ilhaan** [comment]
> I think as you can only use cilium network policies with cilium dataplane and overlay it might be wise to also set this.
> 
> ```yaml
>     networkPolicy: networkDataplane == 'cilium' ? 'cilium' : networkPolicy
>     networkPluginMode: networkDataplane == 'cilium' ? 'overlay' : networkPluginMode
> ```

@cv-gh Please address the comment by @PixelRobots above and also include a pipeline badge for your branch (refer to [this](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/#6-create-a-pull-request-to-the-public-bicep-registry) for more info).

**Comment by ilhaan** [comment]
@cv-gh The pipeline badge needs to be for a run of the `container-service/managed-cluster` module from your branch.

**Comment by AlexanderSehr** [comment]
> @cv-gh The pipeline badge needs to be for a run of the `container-service/managed-cluster` module from your branch.

Updated the badge on @cv-gh's behalf. @cv-gh, I'd recommend the following actions to go foward:
1. Run [this workflow](https://github.com/cv-gh/bicep-registry-modules/actions/workflows/platform.toggle-avm-workflows.yml) to disable all workflows in your fork. This will prevent that the 'trigger on main' will ever trigger all your workflows when you merge the latest upstream changes back into your fork
2. Navigate to the [AKS workflow](https://github.com/cv-gh/bicep-registry-modules/actions/workflows/avm.res.container-service.managed-cluster.yml) and enable it specifically
3. Run the pipeline for your branch, `patch-1`. The badge I updated in your PR's description will automatically reflect the outcome. If there are any findings, the workflow will fail and you'd be asked to work through the error messages (e.g., failed static tests etc.). One the pipeline is eventually green, we're good to go to merge.

**Comment by AlexanderSehr** [comment]
Unfortunately, this PR is dependent on #3228 which we should merge ASAP to unblock @cv-gh . Please excuse the inconvenice 👀

**Pull request closed without merging**
