### PR TITLE
fix: added support for user mi `avm/res/search/search-service`

### LINKED ISSUE #2199: [AVM Module Issue]: Search Service - Does not support User MI
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/search/search-service

### (Optional) Module Version

0.4.2

### Description

Existing version does not support User Managed Identity.
It is available in Microsoft.Search/searchServices@2024-03-01-preview

### (Optional) Correlation Id

_No response_

### PR DESCRIPTION
**Pull request by rajeshkaremane**
## Description
Added support for User Managed Identity

Fixes #2199 

## Pipeline Reference

[avm.res.search.search-service](https://github.com/Azure/bicep-registry-modules/actions/workflows/avm.res.search.search-service.yml) (using a temporary branch)

## Type of Change

- [ ] Update to CI Environment or utilities (Non-module affecting changes)
- [ ] Azure Verified Module updates:
  - [x] Bugfix containing backwards-compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [x] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [ ] I have run `Set-AVMModule` locally to generate the supporting module files.
- [ ] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Comment by matebarabas** [comment]
@krbar, as the owner of this module, please take a look. Thanks!

**Review by krbar — COMMENTED** [review]
@rajeshkaremane Thank you very much for your contribution! Could you by any chance attach a pipeline badge showing that the module passes all validations?

**Comment by rajeshkaremane** [comment]
> @rajeshkaremane Thank you very much for your contribution! Could you by any chance attach a pipeline badge showing that the module passes all validations?

Hi,
I have deployed using an internal pipeline
https://dev.azure.com/defragovuk/DEFRA-FFC/_apis/build/status%2FADP%2FCore%2Fplatform-adp-core-env?repoName=DEFRA%2Fadp-infrastructure-core&branchName=rv%2F382090-openaiinfra

**Comment by krbar** [comment]
@rajeshkaremane 
Thank you, I tested the module and it required a few minor updates:
- conflict resolution of conflict caused by the recently merged #2350
- addressed some readme inconstencies: missing comma and differences in API version which were causing static validation failures
- addressed a BCP321 warning

Now the module looks fine and passes all tests,
@Azure/avm-core-team-technical-bicep please review the changes as I added some new code to the PR and cannot approve it any more. The changes have been tested in a (temporary) branch `users/krbr/pr2200test` which I will delete after merging this PR.

Here is a pipeline badge: [avm.res.search.search-service](https://github.com/Azure/bicep-registry-modules/actions/workflows/avm.res.search.search-service.yml) (the final test still runs)

**Comment by rajeshkaremane** [comment]
Thanks @krbar. Looks like the pipeline has failed due to existing resource with same name . Could you please delete the resource and rerun thanks

**Comment by rajeshkaremane** [comment]
Looks good to me. You should now be able to approve the PR

**Comment by krbar** [comment]
> Looks good to me. You should now be able to approve the PR

Waiting for a green pipeline validation, which is still running

**Review by krbar — APPROVED** [review]

**Comment by rajeshkaremane** [comment]
Hi, @krbar Where can I see the version tags being applied?

**Comment by AlexanderSehr** [comment]
Hey @rajeshkaremane the most straightforward way I know of is directly in the pipeline log: https://github.com/Azure/bicep-registry-modules/actions/runs/9694279814/job/26753261544#step:4:291

**Pull request merged**
