### PR TITLE
fix: Do not set differential backup interval for Hyperscale tiers

### LINKED ISSUE #2469: [AVM Module Issue]: DiffBackupIntervalInHours Error when provisioning Hyperscale SQL server
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/sql/server

### (Optional) Module Version

0.4.0

### Description

I am trying to deploy this module but facing this error

```
[{"code":"FeatureIsNotAvailableForServiceTier","message":"Updating property DiffBackupIntervalInHours is not available for Hyperscale service tier."}]}]}]}]}]}]}]}
```

module
```bicep
param name string
param dbName string
param location string
param virtualNetwork string
param subnet string
param tags object = {}

module server 'br/public:avm/res/sql/server:0.4.0' = {
  name: 'serverDeployment'
  params: {
    // Required parameters
    name: name
    // Non-required parameters
    administrators: {
      azureADOnlyAuthentication: true
      login: 'vanshmittal_debug@prdtrs01.prod.outlook.com'
      principalType: 'Application'
      sid: '0d4f76d6-b3a5-4693-90c8-cd23c7009b57'
      tenantId: 'cdc5aeea-15c5-4db6-b079-fcadd2505dc2'
    }
    databases: [
      {
        backupLongTermRetentionPolicy: {
            monthlyRetention: 'PT0S'
        }
        backupShortTermRetentionPolicy: {
            retentionDays: 7
        }
        capacity: 0
        collation: 'SQL_Latin1_General_CP1_CI_AS'
        licenseType: 'LicenseIncluded'
        maxSizeBytes: 34359738368
        name: dbName
        skuName: 'HS_Gen5'
        skuTier: 'Hyperscale'
        skuCapacity: 4
      }
    ]
    location: location
    managedIdentities: {
      systemAssigned: true
    }
    restrictOutboundNetworkAccess: 'Disabled'
    securityAlertPolicies: [
      {
        emailAccountAdmins: true
        name: 'Default'
        state: 'Enabled'
      }
    ]
    tags: tags
    virtualNetworkRules: [
      {
        ignoreMissingVnetServiceEndpoint: true
        name: 'newVnetRule1'
        virtualNetworkSubnetId: resourceId('Microsoft.Network/virtualNetworks/subnets', virtualNetwork, subnet)
      }
    ]
  }
}

```

### (Optional) Correlation Id

_No response_

### PR DESCRIPTION
**Pull request by peterbud**
There are no Hyperscale tests in the repo (if needed we can add), but I have tested it with an ad-hoc test.

Fixes #2469

## Pipeline Reference

| Pipeline |
| -------- |
|     [avm.res.sql.server](https://github.com/peterbud/bicep-registry-modules/actions/workflows/avm.res.sql.server.yml)     |

pls note: Maintenance window is not available in my subscription, hence WAF test is failing.

## Type of Change

- [ ] Update to CI Environment or utilities (Non-module affecting changes)
- [ ] Azure Verified Module updates:
  - [x] Bugfix containing backwards-compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [ ] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [ ] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Review by AlexanderSehr — APPROVED** [review]

**Comment by peterbud** [comment]
@AlexanderSehr workflow run has failed at the pester test. I have checked, it runs without error with bicep 0.30.23 (that was the latest version up to yesterday). With bicep 0.31.34 it fails. Are you aware of any breaking changes?

Here is the error in the audit-settings module:
/workspaces/bicep-registry-modules/avm/res/sql/server/audit-settings/main.bicep(53,10) : Error BCP036: The property "scope" expected a value of type "resourceGroup" but the provided value is of type "{ id: string, location: string, managedBy: string, name: string, properties: properties, tags: Tags, type: string }". [https://aka.ms/bicep/core-diagnostics#BCP036]

That's the relevant part, and I could not figure out what's wrong with this suddenly with the new compiler:

```bicep
module storageAccount_sbdc_rbac 'modules/nested_storageRoleAssignment.bicep' = if (isManagedIdentityInUse && !empty(storageAccountResourceId)) {
  name: '${server.name}-stau-rbac'
  scope: (isManagedIdentityInUse && !empty(storageAccountResourceId))
    ? resourceGroup(split(storageAccountResourceId!, '/')[2], split(storageAccountResourceId!, '/')[4])
    : resourceGroup()
  params: {
    storageAccountName: last(split(storageAccountResourceId!, '/'))
    managedInstanceIdentityPrincipalId: server.identity.principalId
  }
}
```

**Comment by peterbud** [comment]
OK, I see that you already submitted an issue to the bicep repo. Thx!

**Comment by AlexanderSehr** [comment]
Was just about to write. https://github.com/Azure/bicep/issues/15517, for reference  💪

**Comment by AlexanderSehr** [comment]
Thanks for troubleshooting. It's much appreciated 🙏

**Pull request merged**
