### PR TITLE
feat: `avm/res/db-for-postgre-sql/flexible-server` Align createMode allowed values with API version

### PR DESCRIPTION
**Pull request by VZhuck**
According https://learn.microsoft.com/en-us/azure/templates/microsoft.dbforpostgresql/2022-12-01/flexibleservers?pivots=deployment-language-bicep createMode	values could be 'Create', 'Default', 'GeoRestore', 'PointInTimeRestore', 'Replica', 'Update'

Replica needed to created dependent replica server

## Pipeline Reference

| Pipeline |
| -------- |
|          |

## Type of Change

- [x] Update to CI Environment or utlities (Non-module effecting changes)
- [x] Azure Verified Module updates:
  - [x] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [ ] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [ ] I have run `Set-AVMModule` locally to generate the supporting module files.
- [ ] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Comment by eriqua** [comment]
> Might need additional change, currently testing

Hi @VZhuck thanks for your contribution! I've moved your PR to draft so that you can move it to ready for review once testing is completed 🙂

**Comment by eriqua** [comment]
@josearper would you have some time to please review this PR?

**Comment by AlexanderSehr** [comment]
Hey @VZhuck,
it has been a while. Would you say you're still working on the PR and condluded your testing, or should we close it and start from scratch? :)

**Comment by VZhuck** [comment]
@AlexanderSehr 
I have completed my changes I've been waiting confirmation from your side, so that changes can be merged to main. 
Please let me know if you need anything from my side.

**Comment by eriqua** [comment]
Hey @josearper I see you've been assigned by @arnoldna to review this PR. Is it something you would have availability to do? 

Meanwhile hope you don't mind if I chime in 🙂 

@VZhuck please be aware that as per the [AVM contribution guidelines](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/), you should run the Set-AVMModule utility as detailed [here](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/generate-bicep-module-files/). You will see both the main.json and the README.md files will be updated by that.
Those updates are required for the validation pipeline to succeed and the contribution to be published.

Please reach out if any support needed.

**Comment by eriqua** [comment]
@VZhuck @arnoldna any update on this PR?
Sorry for chasing, an unfortunate effect of the PR staying open for long is that the chance of getting merge conflicts increases. Please reach out if any support required 💪

**Comment by AlexanderSehr** [comment]
> Hey @josearper I see you've been assigned by @arnoldna to review this PR. Is it something you would have availability to do?
> 
> Meanwhile hope you don't mind if I chime in 🙂
> 
> @VZhuck please be aware that as per the [AVM contribution guidelines](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/), you should run the Set-AVMModule utility as detailed [here](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/generate-bicep-module-files/). You will see both the main.json and the README.md files will be updated by that. Those updates are required for the validation pipeline to succeed and the contribution to be published.
> 
> Please reach out if any support needed.

+1 on that :)

**Comment by AlexanderSehr** [comment]
As it does not appears there's any traction, I'll go ahead an merge this PR in a staging branch to finish it from there.

**Pull request merged**
