### PR TITLE
feat: `avm/res/app-configuration/configuration-store`

### LINKED ISSUE #1323: [AVM Module Issue]: App Configuration does not output endpoint
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/app-configuration/configuration-store

### (Optional) Module Name if not listed above

_No response_

### (Optional) Module Version

0.1.1

### Description

Many operations (including, for example, creating a new app configuration settings) require the "endpoint".  Output the endpoint property of the app configuration resource.

(Inbound - will do a PR for this)

### (Optional) Correlation Id

_No response_

### PR DESCRIPTION
**Pull request by adrianhall**
## Description

Closes #1323 

Adds an 'endpoint' output

## Pipeline Reference

Pipeline in my account is failing due to PSRule and ReadMe failures in static analysis, but these same errors are occurring in the mainline, so they are not due to my changes.  The Pester test for the README seems to be innocuous (it is detecting a difference in line endings only).  See https://github.com/adrianhall/bicep-registry-modules/actions/runs/8332755529

## Type of Change

- [ ] Update to CI Environment or utlities (Non-module effecting changes)
- [X] Azure Verified Module updates:
  - [X] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [X] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [X] Update to documentation

## Checklist

- [X] I'm sure there are no other open Pull Requests for the same update/change
- [X] I have run `Set-AVMModule` locally to generate the supporting module files.
- [ ] My corresponding pipelines / checks run clean and green without any errors or warnings

The app-configuration pipeline does not run green on mainline due to errors in WAF Reliability section - nothing to do with this check in.  I'm not volunteering for owning the current state of the module.

### CODE REVIEW

**Review by krbar — COMMENTED** [review]
@adrianhall Thank you for your contribution. The issues you are having, are related to the recent issue #1315 caused by updated formatting introduced with the newest Bicep version. The fix to this issue is under development and there is already a draft PR fixing it: #1321 .
Unfortunately we have to wait for the fix before we will be able to merge your PR.

**Comment by adrianhall** [comment]
Ack - once 1315 is done, I can merge the changes into this branch and test properly.

**Comment by AlexanderSehr** [comment]
> @adrianhall Thank you for your contribution. The issues you are having, are related to the recent issue #1315 caused by updated formatting introduced with the newest Bicep version. The fix to this issue is under development and there is already a draft PR fixing it: #1321 . Unfortunately we have to wait for the fix before we will be able to merge your PR.

Hey @krbar actually we should be able to go ahead as the issue only is an issue for the test files which were not reformatted via this PR.

**Comment by adrianhall** [comment]
Since @AlexanderSehr has said #1315 is not an issue, can we merge this one?

**Comment by krbar** [comment]
> Since @AlexanderSehr has said #1315 is not an issue, can we merge this one?

#1315 is merged, could you please pull the newest changes into your branch and re-run the pipeline? Even if the ignore the WAF Reliability issues, I would like to see a green Static Validation and green Deployment Tests.
This will probably require two runs: 
- one with the static validation (which will probably fail on the WAF reiliability tests)
- one with skipped static validation, which should proceed directly to Deployment Tests
image


Thank you!

**Comment by adrianhall** [comment]
image

This is the first one (with static analysis) - as predicted, the WAF Reliability bits failed.

The deployment tests failed but they are unrelated to the change.  Running deployment tests on main also fail.

**Comment by krbar** [comment]
> The deployment tests failed but they are unrelated to the change. Running deployment tests on main also fail.

Thanks for update! Are you sure that your CI Environment works fine? I just run the deployment validation from the `main` branch of the BRM repo (without the static validation) and it finishes successfully: https://github.com/Azure/bicep-registry-modules/actions/runs/8379871970

The [error message in your fork](https://github.com/adrianhall/bicep-registry-modules/actions/runs/8379223440/job/22945617060#step:4:433) indicates that you may have an issue with the token replacement. Did you set [all required secrets](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/#31-set-up-secrets), especially the `TOKEN_NAMEPREFIX`?

**Comment by adrianhall** [comment]
I've already spent way more time than necessary on this, so I'm going to close this PR as I can't put any more effort into it.

**Pull request closed without merging**
