### PR TITLE
Update GameDev VM Skews

### PR DESCRIPTION
**Pull request by dciborow**
## Description

If you haven't already, read the full [contribution guide](https://github.com/Azure/bicep-registry-modules/blob/main/CONTRIBUTING.md). The guide may have changed since the last time you read it, so please double-check. Once you are done and ready to submit your PR, edit the PR description and run through the relevant checklist below.

Enable GitHub Worksflows in your fork to enable auto-generation of assets with our [GitHub Action](/.github/workflows/push-auto-generate.yml).
To trigger GitHub Actions after auto-generation, [add a GitHub PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) as a secret in your forked repository called `PAT`.

## Adding a new module

- [ ] A proposal has been submitted and approved.
- [ ] I have included "Closes #{module_proposal_issue_number}" in the PR description.
- [ ] I have run `brm validate` locally to verify the module files.
- [ ] I have run deployment tests locally to ensure the module is deployable.

## Updating an existing module

- [x] This is a bug fix:
  - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
  - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
- [x] I have run `brm validate` locally to verify the module files.
- [x] I have run deployment tests locally to ensure the module is deployable.
- [x] I have read the [Updating an existing module](https://github.com/Azure/bicep-registry-modules/blob/main/CONTRIBUTING.md#updating-an-existing-module) section in the contributing guide and updated the `version.json` file properly:
  - [ ] The PR contains backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`.
  - [ ] The PR contains backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [x] The PR contains breaking changes, and I have bumped the MAJOR version in `version.json`.
- [x] I have updated the examples in README with the latest module version number.

### CODE REVIEW

**Comment by dciborow** [comment]
@shenglol ,
Do you know how to fix this for me?
```
[31;1mNew-AzResourceGroupDeployment: [31;1m7:28:26 PM - Error: Code=MarketplacePurchaseEligibilityFailed; Message=Marketplace purchase eligibilty check returned errors. See inner errors for details. 
[0m
[31;1mNew-AzResourceGroupDeployment: [31;1m7:28:26 PM - Error: Code=BadRequest; Message=Offer with PublisherId: 'microsoft-azure-gaming', OfferId: 'game-dev-vm' cannot be purchased due to validation errors. For more information see details. Correlation Id: 'ac4ac901-cf0a-411d-a459-15607140bf4c' You have not accepted the legal terms on this subscription: '3ce675b8-fcea-4732-a965-393bbe02d7ad' for this plan. Before the subscription can be used, you need to accept the legal terms of the image. To read and accept legal terms, use the Azure CLI commands described at https://go.microsoft.com/fwlink/?linkid=2110637 or the PowerShell commands available at https://go.microsoft.com/fwlink/?linkid=862451. Alternatively, deploying via the Azure portal provides a UI experience for reading and accepting the legal terms. Offer details: publisher='microsoft-azure-gaming' offer = 'game-dev-vm', sku = 'win11_no_engine_1_0', Correlation Id: 'ac4ac901-cf0a-411d-a459-15607140bf4c'.[{"You have not accepted the legal terms on this subscription: '3ce675b8-fcea-4732-a965-393bbe02d7ad' for this plan. Before the subscription can be used, you need to accept the legal terms of the image. To read and accept legal terms, use the Azure CLI commands described at https://go.microsoft.com/fwlink/?linkid=2110637 or the PowerShell commands available at https://go.microsoft.com/fwlink/?linkid=862451. Alternatively, deploying via the Azure portal provides a UI experience for reading and accepting the legal terms. Offer details: publisher='microsoft-azure-gaming' offer = 'game-dev-vm', sku = 'win11_no_engine_1_0', Correlation Id: 'ac4ac901-cf0a-411d-a459-15607140bf4c'.":"StoreApi"}]
[0m
[31;1mNew-AzResourceGroupDeployment: [31;1mThe deployment validation failed[0m
```

**Comment by shenglol** [comment]
> @shenglol , Do you know how to fix this for me? There is a CLI command to accept the terms for the image. I'm not sure this changed.
> 
> ```
> �[31;1mNew-AzResourceGroupDeployment: �[31;1m7:28:26 PM - Error: Code=MarketplacePurchaseEligibilityFailed; Message=Marketplace purchase eligibilty check returned errors. See inner errors for details. 
> �[0m
> �[31;1mNew-AzResourceGroupDeployment: �[31;1m7:28:26 PM - Error: Code=BadRequest; Message=Offer with PublisherId: 'microsoft-azure-gaming', OfferId: 'game-dev-vm' cannot be purchased due to validation errors. For more information see details. Correlation Id: 'ac4ac901-cf0a-411d-a459-15607140bf4c' You have not accepted the legal terms on this subscription: '3ce675b8-fcea-4732-a965-393bbe02d7ad' for this plan. Before the subscription can be used, you need to accept the legal terms of the image. To read and accept legal terms, use the Azure CLI commands described at https://go.microsoft.com/fwlink/?linkid=2110637 or the PowerShell commands available at https://go.microsoft.com/fwlink/?linkid=862451. Alternatively, deploying via the Azure portal provides a UI experience for reading and accepting the legal terms. Offer details: publisher='microsoft-azure-gaming' offer = 'game-dev-vm', sku = 'win11_no_engine_1_0', Correlation Id: 'ac4ac901-cf0a-411d-a459-15607140bf4c'.[{"You have not accepted the legal terms on this subscription: '3ce675b8-fcea-4732-a965-393bbe02d7ad' for this plan. Before the subscription can be used, you need to accept the legal terms of the image. To read and accept legal terms, use the Azure CLI commands described at https://go.microsoft.com/fwlink/?linkid=2110637 or the PowerShell commands available at https://go.microsoft.com/fwlink/?linkid=862451. Alternatively, deploying via the Azure portal provides a UI experience for reading and accepting the legal terms. Offer details: publisher='microsoft-azure-gaming' offer = 'game-dev-vm', sku = 'win11_no_engine_1_0', Correlation Id: 'ac4ac901-cf0a-411d-a459-15607140bf4c'.":"StoreApi"}]
> �[0m
> �[31;1mNew-AzResourceGroupDeployment: �[31;1mThe deployment validation failed�[0m
> ```

Not sure if this is related to a recent change Marcin made to the subscription, so we need to accept the legal terms again. Let me try to fix that.

**Comment by shenglol** [comment]
Turns out the test subscription got disabled. Am figuring out the reason and trying to reactivate it.

**Review by shenglol — APPROVED** [review]

**Pull request merged**
