### PR TITLE
feat: `avm/res/cognitive-services/account` Added endpoints to outputs

### LINKED ISSUE #2611: [AVM Module Issue]: Cognitive Services Module should add the output `account.properties.endpoints`
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/cognitive-services/account

### (Optional) Module Version

_No response_

### Description

Please add the output `account.properties.endpoints`.

For example (azd):

- https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/ai/cognitiveservices.bicep#L54

CC: @jongio

### (Optional) Correlation Id

_No response_

### PR DESCRIPTION
**Pull request by donheerschap**
## Description

Added endpoints properties to output
closes https://github.com/Azure/bicep-registry-modules/issues/2611

## Pipeline Reference

| Pipeline |
| -------- |
|  [avm.res.cognitive-services.account](https://github.com/donheerschap/bicep-registry-modules/actions/workflows/avm.res.cognitive-services.account.yml)|

## Type of Change

- [ ] Update to CI Environment or utilities (Non-module affecting changes)
- [x] Azure Verified Module updates:
  - [ ] Bugfix containing backwards-compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [x] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [x] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Comment by donheerschap** [comment]
Hi @ilhaan I needed this for a project with OpenAI and I saw there was an issue open which required this feature aswell. Hope you can review this soon!

**Review by ilhaan — DISMISSED** [review]
@donheerschap LGTM. Thank you!

**Comment by AlexanderSehr** [comment]
Hey @donheerschap @ilhaan,
please note that another PR was merged in the meantime. That means that you @donheerschap need to fetch latest upstream, merge the changes into your branch, resolve the conflicts & run the `Set-AVMModule` script again. I would not advice to just resolve the conflicts via GitHub as the template hash will likely change.
@ilhaan you'd then need to re-approve 💪

**Comment by donheerschap** [comment]
Resolved conflicts @ilhaan @AlexanderSehr

**Review by AlexanderSehr — APPROVED** [review]

**Comment by AlexanderSehr** [comment]
@ilhaan, will approve and monitor given that you already approved it and it was only awaiting the conflict resultion

**Pull request merged**
