### PR TITLE
feat(new): Azure Data Explorer (Kusto)

### PR DESCRIPTION
**Pull request by vlahane**
## Description
closes: https://github.com/Azure/bicep-registry-modules/issues/287

If you haven't already, read the full [contribution guide](https://github.com/Azure/bicep-registry-modules/blob/main/CONTRIBUTING.md). The guide may have changed since the last time you read it, so please double-check. Once you are done and ready to submit your PR, edit the PR description and run through the relevant checklist below.

Enable GitHub Worksflows in your fork to enable auto-generation of assets with our [GitHub Action](/.github/workflows/push-auto-generate.yml).
To trigger GitHub Actions after auto-generation, [add a GitHub PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) as a secret in your forked repository called `PAT`.

## Adding a new module

- [x] A proposal has been submitted and approved.
- [x] I have included "Closes #{module_proposal_issue_number}" in the PR description.
- [x] I have run `brm validate` locally to verify the module files.
- [x] I have run deployment tests locally to ensure the module is deployable.

### CODE REVIEW

**Comment by vlahane** [comment]
@dciborow  please review created from your PR,

Error:

##[error]New-AzResourceGroupDeployment: 12:40:51 PM - The deployment 'main.test' failed with error(s). Showing 2 out of 2 error(s).
Status Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details. (Code: DeploymentFailed)
 - The subscription is not registered to use namespace 'Microsoft.Kusto'. See https://aka.ms/rps-not-found for how to register subscriptions. (Code: MissingSubscriptionRegistration)
   - The subscription is not registered to use namespace 'Microsoft.Kusto'. See https://aka.ms/rps-not-found for how to register subscriptions. (Code:MissingSubscriptionRegistration)
Status Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details. (Code: DeploymentFailed)
 - The subscription is not registered to use namespace 'Microsoft.Kusto'. See https://aka.ms/rps-not-found for how to register subscriptions. (Code: MissingSubscriptionRegistration)
   - The subscription is not registered to use namespace 'Microsoft.Kusto'. See https://aka.ms/rps-not-found for how to register subscriptions. (Code:MissingSubscriptionRegistration)
CorrelationId: 671d00fe-cffa-42b1-a1ee-197455c18908

**Comment by shenglol** [comment]
There are errors in the test file:

```
[31;1mNew-AzResourceGroupDeployment: [31;1mCannot retrieve the dynamic parameters for the cmdlet. WARNING: Symbolic name support in ARM is experimental, and should be enabled for testing purposes only. Do not enable this setting for any production usage, or you may be unexpectedly broken at any time!
D:\a\1\s\modules\storage\data-explorer\test\prereq.test.bicep(48,21) : Error BCP036: The property "kind" expected a value of type "error | null" but the provided value is of type "'Hash'".
D:\a\1\s\modules\storage\data-explorer\test\main.test.bicep(13,15) : Error BCP104: The referenced module has errors.[0m
```

**Comment by vlahane** [comment]
> There are errors in the test file:
> 
> ```
> �[31;1mNew-AzResourceGroupDeployment: �[31;1mCannot retrieve the dynamic parameters for the cmdlet. WARNING: Symbolic name support in ARM is experimental, and should be enabled for testing purposes only. Do not enable this setting for any production usage, or you may be unexpectedly broken at any time!
> D:\a\1\s\modules\storage\data-explorer\test\prereq.test.bicep(48,21) : Error BCP036: The property "kind" expected a value of type "error | null" but the provided value is of type "'Hash'".
> D:\a\1\s\modules\storage\data-explorer\test\main.test.bicep(13,15) : Error BCP104: The referenced module has errors.�[0m
> ```

I think, this must be a bug in bicep, https://github.com/Azure/bicep-registry-modules/blob/de40c8001ffa0a74fe81f7c55408c8a38c110421/modules/storage/cosmos-db/test/main.test.bicep#L365
referencing module from repository might introduce some error, as per I remember this was working last month.  

@shenglol will you please check

**Comment by shenglol** [comment]
> > There are errors in the test file:
> > ```
> > �[31;1mNew-AzResourceGroupDeployment: �[31;1mCannot retrieve the dynamic parameters for the cmdlet. WARNING: Symbolic name support in ARM is experimental, and should be enabled for testing purposes only. Do not enable this setting for any production usage, or you may be unexpectedly broken at any time!
> > D:\a\1\s\modules\storage\data-explorer\test\prereq.test.bicep(48,21) : Error BCP036: The property "kind" expected a value of type "error | null" but the provided value is of type "'Hash'".
> > D:\a\1\s\modules\storage\data-explorer\test\main.test.bicep(13,15) : Error BCP104: The referenced module has errors.�[0m
> > ```
> 
> I think, this must be a bug in bicep,
> 
> https://github.com/Azure/bicep-registry-modules/blob/de40c8001ffa0a74fe81f7c55408c8a38c110421/modules/storage/cosmos-db/test/main.test.bicep#L365
> 
> 
> referencing module from repository might introduce some error, as per I remember this was working last month.
> @shenglol will you please check

Yeah, this does seem to be a bug. I created an issue to track this. For now, I think we can use the `any` function as a workaround to bypass type checking:
```
            ...
            partitionKey: {
              kind: any('Hash')
            }
            ...

```

**Comment by vlahane** [comment]
@shenglol  I think instead of using workaround, as fix is merge can't we get new bicep release out soon?

**Comment by shenglol** [comment]
> @shenglol I think instead of using workaround, as fix is merge can't we get new bicep release out soon?

We don't have a plan to do another 20.x release since the bug only affects ARM template modules. We will be publishing 21.x early next month,

**Comment by vlahane** [comment]
@shenglol changes are done updated with any, thanks! :)

**Review by shenglol — APPROVED** [review]

**Pull request merged**
