### PR TITLE
feat: Updated remaining templates with deployment-linter suppression

### LINKED ISSUE #1344: [AVM Question/Feedback]: Supress 'no-deployments' resource warnings
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Currently, when using an AVM module, users see a warnings for the `Microsoft.Resources/deployments` deployment that we use for the telemetry tracking. While a best-practice, this design was choises in this case for a purpose.
We should investigate if we can either supress it, or, if not, change the implementation to not cause it.

> Warning no-deployments-resources: Resource 'avmTelemetry' of type 'Microsoft.Resources/deployments@2023-07-01' should instead be declared as a Bicep module

Mind you: Supressing it in the `bicepconfig.json` file will not be enough.

### PR DESCRIPTION
**Pull request by AlexanderSehr**
## Description

Updated reamining templates with deployment-linter suppression

Replaces
- #2355
- #2353

Closes #1344

## Type of Change

- [ ] Update to CI Environment or utilities (Non-module affecting changes)
- [x] Azure Verified Module updates:
  - [ ] Bugfix containing backwards-compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [ ] Update to documentation

### CODE REVIEW

**Review by gbeaud — DISMISSED** [review]

**Review by ReneHezser — DISMISSED** [review]

**Review by arnoldna — DISMISSED** [review]

**Review by peterbud — DISMISSED** [review]

**Review by oZakari — DISMISSED** [review]

**Review by judyer28 — DISMISSED** [review]

**Review by arnoldna — DISMISSED** [review]

**Review by eriqua — COMMENTED** [review]
Surprisingly this got conflicts again 😄 

@AlexanderSehr if that does not happen before, please ping me on Wednesday if conflicts are resolved and I'll see to approve

**Comment by AlexanderSehr** [comment]
> Surprisingly this got conflicts again 😄
> 
> @AlexanderSehr if that does not happen before, please ping me on Wednesday if conflicts are resolved and I'll see to approve

Hey @eriqua, I'll try to take care of this on Wednesday. Would you consider the PR itself to be reviewed? If bad comes to worse, I'l ask any one of the maintainers to just approve if the case so that we don't keep the PR around for longer.

**Comment by AlexanderSehr** [comment]
Hey @eriqua, I now resolved the latest conflicts again. Please take a look.

**Review by eriqua — APPROVED** [review]
🆗

**Pull request merged**
