### PR TITLE
feat: Retiring non-AVM modules

### PR DESCRIPTION
**Pull request by matebarabas**
As part of the retirement process of the non-AVM modules, this PR:
- Removes the source code of 26 modules.
- Adds a `REPLACED.md` or `RETIRED.md` file with information on what's happening to the module, and what's the replacement module - if applicable.
- Adds the same content to the top of the `README.md` file.
- Adds an `ARCHIVED.md` file that lists all the previous versions of the module that were ever released.

Dependencies (this PR cannot be merged before these AVM modules are published):
- [avm/res/app-configuration/configuration-store](https://github.com/Azure/Azure-Verified-Modules/issues/681) - [in PR](https://github.com/Azure/bicep-registry-modules/pull/1072)
- [avm/res/event-hub/namespace](https://github.com/Azure/Azure-Verified-Modules/issues/611) - @elanzel, please prioritize this work as it's blocking this PR. Thanks!

This PR retires:

- `ai/bing-resource`
- `ai/cognitiveservices`
- `app/app-configuration`
- `authorization/resource-scope-role-assignment`
- `compute/availability-set`
- `compute/container-registry`
- `compute/event-hub`
- `compute/function-app`
- `identity/user-assigned-identity`
- `network/dns-zone`
- `network/nat-gateway`
- `network/private-dns-zone`
- `network/public-ip-address`
- `network/public-ip-prefix`
- `network/traffic-manager`
- `network/virtual-network`
- `samples/array-loop`
- `samples/hello-world`
- `search/search-service`
- `security/keyvault`
- `storage/cosmos-db`
- `storage/log-analytics-workspace`
- `storage/mysql-single-server`
- `storage/postgresql-single-server`
- `storage/redis-cache`
- `storage/storage-account`

### CODE REVIEW

**Review by ChrisSidebotham — APPROVED** [review]
lgtm

**Review by shenglol — APPROVED** [review]
:shipit:

**Comment by elanzel** [comment]
opened https://github.com/Azure/bicep-registry-modules/pull/1138 for blocking eventhub module

**Comment by ChrisSidebotham** [comment]
@shenglol - With the nature of this PR is there anything we can do surrounding this failing check 
image

**Comment by shenglol** [comment]
> @shenglol - With the nature of this PR is there anything we can do surrounding this failing check image

We can temporarily update the branch protection rules and force merge the PR since it won't trigger module publish.

**Pull request merged**
