### PR TITLE
fix: Site module app insight and customDomainVerificationId

### PR DESCRIPTION
**Pull request by pankajagrawal16**
## Description

This PR fixes two issues in site module:

- Currently, if user of the module does not specify any appSettingsKeyValuePairs but only appInsightResourceId, the relevant app settings for configuring app insights is not created by the module since the bicep code only checks for appSettingsKeyValuePairs emptiness.
- Remove misleading customDomainVerificationId as param. This is a read only property and set after app service instance is created. Exposed the same as output instead.
- https://stackoverflow.com/questions/69382365/setting-the-customdomainverificationid-property-on-an-appservice-in-a-bicep-de

## Pipeline Reference

| Pipeline |
| -------- |
|   [avm.res.web.site](https://github.com/pankajagrawal16/bicep-registry-modules/actions/workflows/avm.res.web.site.yml)    |

## Type of Change

- [x] Update to CI Environment or utilities (Non-module affecting changes)
- [x] Azure Verified Module updates:
  - [x] Bugfix containing backwards-compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [x] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [x] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [x] Update to documentation

## Checklist

- [ ] I'm sure there are no other open Pull Requests for the same update/change
- [x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Comment by pankajagrawal16** [comment]
@tsc-buddy Have a look. I closed this PR https://github.com/Azure/bicep-registry-modules/pull/2465 and instead combined two issues and refreshed branch etc.

**Comment by pankajagrawal16** [comment]
Hi Team,

Can some one review this and progress further? cc @tsc-buddy

**Comment by AlexanderSehr** [comment]
> Hi Team,
> 
> Can some one review this and progress further? cc @tsc-buddy

Hey @pankajagrawal16,
I just pinged @tsc-buddy on the side. If bad comes to worse, one of us maintainers can certainly review the PR. However, I can see that there is a conflict in the main.json which I'd need to ask you to resolve. I'd recommend to get whatever change into your PR and then just re-run the `Set-AVMModule` script to make sure the contained templateHash etc. is definitely representing your version of the code 💪

**Review by tsc-buddy — DISMISSED** [review]
Im happy with these, thanks @pankajagrawal16. The appsettings condition will be useful.

**Review by tsc-buddy — APPROVED** [review]

**Pull request merged**
