### PR TITLE
feat: StorageAccount - Added allowed tier value, updated local user authorized key interface, added udts

### LINKED ISSUE #3629: [AVM Module Issue]: Storage Account module missing Cold accessTier
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/storage/storage-account

### (Optional) Module Version

_No response_

### Description

The Storage Account module allows values 'Premium', 'Hot' and 'Cool' for the 'accessTier' parameter https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/storage/storage-account/main.bicep#L41.

As per the bicep resource documentation, 'Cold' is a valid value that is missing from the allowed values above https://learn.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts?pivots=deployment-language-bicep#storageaccountpropertiescreateparametersorstorageacc.

Can the 'Cold' value please be added?

### (Optional) Correlation Id

_No response_

### LINKED ISSUE #3640: [AVM Module Issue]: Improve storage sshAuthorizedKeyType
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/storage/storage-account

### (Optional) Module Version

0.14.x

### Description

Custom type `sshAuthorizedKeysType` in `avm\res\storage\storage-account\local-user` and related usage requires the following updates:

- remove the nested `secureList`
- use `@secure()` metadata for the key property instead
- make the type singular and rename to `sshAuthorizedKeyType`
- add the `[]` to the parameter instead. It should become `param sshAuthorizedKeys sshAuthorizedKeyType[]?`
- once fixed, add the `@export` metadata to the type

### (Optional) Correlation Id

_No response_

### PR DESCRIPTION
**Pull request by AlexanderSehr**
## Description

- Added tier 'Cold'
- Updated local user authorized key handling (secureList)
- Added udts for local user & sub-objects

Depends on https://github.com/microsoft/PSRule/issues/2591 & Release https://github.com/Azure/PSRule.Rules.Azure/milestone/127

Closes #3640
Closes #3629

## Pipeline Reference

| Pipeline |
| -------- |
|     [avm.res.storage.storage-account](https://github.com/Azure/bicep-registry-modules/actions/workflows/avm.res.storage.storage-account.yml)     |

## Type of Change

- [ ] Update to CI Environment or utilities (Non-module affecting changes)
- [ ] Azure Verified Module updates:
  - [ ] Bugfix containing backwards-compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [x] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [ ] Update to documentation

### CODE REVIEW

**Comment by AlexanderSehr** [comment]
@fblix / @ktremain please review when you get the chance. The PR closes to storage account issues.

**Review by eriqua — COMMENTED** [review]
Hola @AlexanderSehr, what about integrating here also changes done in #3606 ?

**Comment by AlexanderSehr** [comment]
> Hola @AlexanderSehr, what about integrating here also changes done in #3606 ?

Can do, sure

**Comment by jtracey93** [comment]
Hey @AlexanderSehr ,

Firstly, thanks for your work on this PR!

We have made some changes to the AVM CI, detailed below, which means we need you to update your fork to pull in these latest changes and re-run your tests to show they still are passing prior to approving and merging this PR, as we don't and it fails once merged the publishing of your module will fail and will be blocked going forward until the test pass again via additional PRs.

### Changes to CI That Have Been Made That You Need To Take Action On

- https://github.com/Azure/bicep-registry-modules/pull/3745
    - Adds WAF Security PSRule Checks using this custom baseline of rules ([`/avm/utilities/pipelines/staticValidation/psrule/.ps-rule/cb-waf-security.Rule.yaml`](https://github.com/Azure/bicep-registry-modules/blob/main/avm/utilities/pipelines/staticValidation/psrule/.ps-rule/cb-waf-security.Rule.yaml))
    - **Action Required By You:**
        - Ingest/pull-in these changes into your PR branch and re-run your tests to ensure they pass
            - If any issues with the rules and you think it should apply, please ping/reach out to the core team

Any questions reach out to the AVM Core Team by tagging us in your PR here or internally via Teams

Thanks

Jack (AVM Core Team)

**Review by ktremain — DISMISSED** [review]

**Review by ktremain — APPROVED** [review]

**Pull request merged**
