### PR TITLE
feat: Updates base image and adds features the nice way, allows local testing

### PR DESCRIPTION
**Pull request by ReneHezser**
## Description

Updates devcontainer
- base image
- installs features via "features"
- allows local GitHub action testing

## Pipeline Reference

not needed

## Type of Change

- [x] Update to CI Environment or utilities (Non-module effecting changes)
- [ ] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [ ] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [ ] I have run `Set-AVMModule` locally to generate the supporting module files.
- [ ] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Comment by ChrisSidebotham** [comment]
@segraef - Are you happy with this?

**Comment by segraef** [comment]
> @segraef - Are you happy with this?

Yup, much more cleaner way, thanks @ReneHezser.

**Review by AlexanderSehr — DISMISSED** [review]
Thanks for reviewing @segraef, will approve on that basis.
And of course thank you @ReneHezser for the contribution 💪

**Comment by AlexanderSehr** [comment]
Dang, prettier takes offense. Very likely because of the file ending: 
image

@ReneHezser could you take care of this?

**Comment by ReneHezser** [comment]
> Dang, prettier takes offense. Very likely because of the file ending: image
> 
> @ReneHezser could you take care of this?

Sorry about that. Done

**Review by AlexanderSehr — DISMISSED** [review]

**Comment by AlexanderSehr** [comment]
@ChrisSidebotham, I think you know more about prettier than me 😄 Would you happen to have any advice? Maybe we can just bypass it by taking the workflow out of the policy as we may or may not retire it anyhow.

**Comment by ChrisSidebotham** [comment]
From my understanding this happens when your editor switches from CRLF to LF and prettier doesn't like it, but we never managed to confirm that

**Comment by AlexanderSehr** [comment]
Closing and Re-opening to re-trigger the workflow validation...

**Comment by AlexanderSehr** [comment]
I'm impressed. Even by removing the workflow requirement and re-opening the PR the check prevails. @ReneHezser at this point the only solutino I'm seeing is to open a new PR from the same branch you opened this one from. Could you give that a shot?

**Comment by ReneHezser** [comment]
I am testing Prettier and its discomfort with this file anyway. CRLF is not the problem.

**Review by AlexanderSehr — APPROVED** [review]

**Pull request merged**
