### PR TITLE
feat: Add bgp community property to `avm/res/network/virtual-network`

### PR DESCRIPTION
**Pull request by johnlokerse**
## Description

This pull request introduces the `virtualNetworkBgpCommunity` parameter which is used in the `bgpCommunities`. Also, the `contains()` functions are replaced with the safe-dereference operator.

Tagging module owner for visibility: @elbatane 

## Pipeline Reference

| Pipeline |
| -------- |
|    [avm.res.network.virtual-network](https://github.com/johnlokerse/bicep-registry-modules/actions/workflows/avm.res.network.virtual-network.yml)      |

## Type of Change

- [ ] Update to CI Environment or utilities (Non-module affecting changes)
- [ ] Azure Verified Module updates:
  - [ ] Bugfix containing backwards-compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [x] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [x] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Comment by johnlokerse** [comment]
Any ETA on this to be merged?

Tagging @AlexanderSehr for review...

**Comment by AlexanderSehr** [comment]
Hey @johnlokerse,
Elena may be out of office. Coincidently, I also started working on a couple of VNET issues in a PR on the side. I'd recommend to do re-direct this PR to that PR's branch (https://github.com/Azure/bicep-registry-modules/pull/3105) so that your changes are properly tracked and I'll undo my changes for the `bgpCommunities` in there, so that your name stands next to that change. It's then still not in main, but at least we don't have multiple conflicting PRs 😄

**Comment by johnlokerse** [comment]
> Hey @johnlokerse, Elena may be out of office. Coincidently, I also started working on a couple of VNET issues in a PR on the side. I'd suggested that I re-direct this PR to that PR's branch (#3105) so that your changes are properly tracked and I'll undo my changes for the `bgpCommunities` in there, so that your name stands next to that change. It's then still not in main, but at least we don't have multiple conflicting PRs 😄

Sounds good to me 😃  The subnetType is a welcome improvement! I have that one in a branch too (not finished) ;-). Thnx @AlexanderSehr 👍

**Comment by AlexanderSehr** [comment]
Great @johnlokerse,
I just changed the target branch. Please resolve the conflicts in the `main.bicep` file and regenerate the `main.json` file after. Once done, we can merge the change in

**Comment by johnlokerse** [comment]
Done! Can you double-check @AlexanderSehr if it's correct?

**Review by AlexanderSehr — APPROVED** [review]
Like a dream come true. Thanks @johnlokerse 🚀

**Pull request merged**
