### PR TITLE
fix: AZD ML Project - Adjusted KeyVault access policies deployment

### PR DESCRIPTION
**Pull request by AlexanderSehr**
## Description

- Fixed AZD ML Project access policies deployment to use native Bicep code. 
- Using the AVM module in this case is not a good idea as it sets several default values (such as purge protection)

## Pipeline Reference

| Pipeline |
| -------- |
|   [avm.ptn.azd.ml-project](https://github.com/Azure/bicep-registry-modules/actions/workflows/avm.ptn.azd.ml-project.yml)       |

## Type of Change

- [ ] Update to CI Environment or utilities (Non-module affecting changes)
- [ ] Azure Verified Module updates:
  - [x] Bugfix containing backwards-compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [ ] Update to documentation

### CODE REVIEW

**Review by eriqua — COMMENTED** [review]
@AlexanderSehr although the avm module sets secure values by default, it should always be possible to overwrite those values by explicitly passing them as input. 
Out of curiosity, why not doing that instead of using the native resource?

**Comment by AlexanderSehr** [comment]
> @AlexanderSehr although the avm module sets secure values by default, it should always be possible to overwrite those values by explicitly passing them as input. Out of curiosity, why not doing that instead of using the native resource?

Great question. I'd advice against it because the unexpected overwrite of the `purgeProtection` that is the original reason I've created this PR may only be one of the properties that's overwritten. There are a lot more defaults in the Key Vault module that I'd need to guess even though the creator actually only wanted to deploy the `accessPolicies` child module. I hope that makes sense :)

**Comment by eriqua** [comment]
> d this PR may only be one of the properties that's overwritten. There are a lot more defaults in the Key Vault module that I'd need to guess even though the creator actually only wanted to deploy the `accessPolicies` child module. I hope that makes sense :)

Fair for me. I guess this can be updated if we get to the child module publishing, right?

**Review by eriqua — APPROVED** [review]
🆗

**Comment by AlexanderSehr** [comment]
> > d this PR may only be one of the properties that's overwritten. There are a lot more defaults in the Key Vault module that I'd need to guess even though the creator actually only wanted to deploy the `accessPolicies` child module. I hope that makes sense :)
> 
> Fair for me. I guess this can be updated if we get to the child module publishing, right?

Definitely 💪

**Pull request merged**
