### PR TITLE
feat: Added `WhatIf` support to `Test-ModuleLocally` script + several smaller bugfixes

### PR DESCRIPTION
**Pull request by AlexanderSehr**
## Description

- Added WhatIf capabilities as per PR: https://github.com/Azure/ResourceModules/pull/4241
- Small fixes in `Test-ModuleLocally` script
- Removed support for JSON parameter files from `Test-ModuleLocally` script
- Updated naming of `Test-Deployment` script to not depend on `Microsoft.` prefix

### CODE REVIEW

**Comment by ChrisSidebotham** [comment]
@AlexanderSehr - Any reason why this is expecting a review from @Azure/avm-res-operationalinsights-workspace-module-owners-bicep?

**Comment by AlexanderSehr** [comment]
> @AlexanderSehr - Any reason why this is expecting a review from @Azure/avm-res-operationalinsights-workspace-module-owners-bicep?

Not sure. I think I've seen in the log that Git was complaining about that module's encoding (-> Line-Ending) so maybe that's why. However, it's not part of the PR so it remains a bit odd. I wish I'd know :D

**Comment by ChrisSidebotham** [comment]
> > @AlexanderSehr
> >             
> >             Alexander Sehr
> >             FTE - Any reason why this is expecting a review from @Azure/avm-res-operationalinsights-workspace-module-owners-bicep?
> 
> Hey @ChrisSidebotham Chris Sidebotham FTE, not sure. I think I've seen in the log that Git was complaining about that module's encoding (-> Line-Ending) so maybe that's why. However, it's not part of the PR so it remains a bit odd. I wish I'd know :D

I see there is now conflicts on this @AlexanderSehr

**Comment by AlexanderSehr** [comment]
> > > @AlexanderSehr
> > > ```
> > >         Alexander Sehr
> > >         FTE - Any reason why this is expecting a review from @Azure/avm-res-operationalinsights-workspace-module-owners-bicep?
> > > ```
> > 
> > 
> > Hey @ChrisSidebotham Chris Sidebotham FTE, not sure. I think I've seen in the log that Git was complaining about that module's encoding (-> Line-Ending) so maybe that's why. However, it's not part of the PR so it remains a bit odd. I wish I'd know :D
> 
> I see there is now conflicts on this @AlexanderSehr

resolved. My fix in main was even more correct than this one :D

**Review by ChrisSidebotham — APPROVED** [review]
👌

**Pull request merged**
