### PR TITLE
feat: Change input parameter to boolean (AKS)

### PR DESCRIPTION
**Pull request by JPEasier**
## Description

update input parameter `string "true" or "false"` to `boolean` 

related https://github.com/Azure/ResourceModules/issues/2546

## Pipeline Reference

| Pipeline |
| -------- |
|    [avm.res.container-service.managed-cluster](https://github.com/JPEasier/bicep-registry-modules/actions/workflows/avm.res.container-service.managed-cluster.yml)    |

## Type of Change

- [ ] Update to CI Environment or utlities (Non-module effecting changes)
- [x] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [x] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [x] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Comment by AlexanderSehr** [comment]
> @AlexanderSehr, @ahmadabdalla, related to the issue [Azure/ResourceModules#2546](https://github.com/Azure/ResourceModules/issues/2546) I have updated some parameters from string to boolean but dont get it running, do you have any idea? maybe I have a typo in code or somthing else.

Hey @JPEasier,
that is, unfortunately, a quick one. The 'string' function interpretation of a boolean changes for an unknown reason the lower-case to an upper-case string.

I ran the following quick test

```bicep
targetScope = 'subscription'

param test bool = true

output testOutput string = string(test)
```

```text
PS C:\dev\ip\bicep-registry-modules\Upstream-Azure> New-AzDeployment -TemplateFile 'C:\outputTest.bicep'  -Location 'WestEurope' -Verbose
VERBOSE: Using Bicep v0.27.1
VERBOSE: Calling Bicep with arguments: build "C:\Users\<user>\OneDrive - Microsoft\Docs\Code\temp\outputTest.bicep" --outdir "C:\Users\<user>\AppData\Local\Temp\1e378fdd-dffa-435e-b59e-33d885105504d"
VERBOSE: 
VERBOSE: 23:24:31 - Template is valid.
VERBOSE: 23:24:33 - Create template deployment 'outputTest'
VERBOSE: 23:24:33 - Checking deployment status in 5 seconds

Id                      : /subscriptions/<subId>/providers/Microsoft.Resources/deployments/outputTe 
                          st
DeploymentName          : outputTest
Location                : westeurope
ProvisioningState       : Succeeded
Timestamp               : 01/06/2024 21:24:33
Mode                    : Incremental
TemplateLink            : 
Parameters              : 
                          Name             Type                       Value
                          ===============  =========================  ==========
  true

Outputs                 : 
                          Name             Type                       Value
                          ===============  =========================  ==========
                          testOutput       String                     "True"

DeploymentDebugLogLevel : 
```

Changing, for example
`output testOutput string = string(test)` 
to
`output testOutput string = toLower(string(test))`
'fixes' the issue:

```text
(...)
Outputs                 : 
                          Name             Type                       Value     
                          ===============  =========================  ==========
                          testOutput       String                     "true"  
(...)
```

**Comment by eriqua** [comment]
@JPEasier would you have some time to please drive this PR to closure?

**Comment by JPEasier** [comment]
Hi @eriqua, I am working on a quick fix for the module first, than come back to this PR, sorry for the delay.

**Comment by JPEasier** [comment]
waiting for #2793

**Comment by AlexanderSehr** [comment]
> waiting for #2793

Not anymore 😉

**Review by ilhaan — APPROVED** [review]

**Pull request merged**
