### PR TITLE
feat: support function app flex consumption plan

### PR DESCRIPTION
**Pull request by pankajagrawal16**
## Description

#3389 
#3316 

## Pipeline Reference

| Pipeline |
| -------- |
|    [avm.res.web.site](https://github.com/pankajagrawal16/bicep-registry-modules/actions/workflows/avm.res.web.site.yml)    [avm.res.web.serverfarm](https://github.com/pankajagrawal16/bicep-registry-modules/actions/workflows/avm.res.web.serverfarm.yml) |

## Type of Change

- [ ] Update to CI Environment or utilities (Non-module affecting changes)
- [x] Azure Verified Module updates:
  - [x] Bugfix containing backwards-compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [x] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [x] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [x] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Comment by pankajagrawal16** [comment]
@tsc-buddy Can you have a look?

**Review by tsc-buddy — COMMENTED** [review]
Looks good - theres a seperate ask for this to support flex consumption functions. Can you also add the appropriate Kind for FlexConsumption into this PR also.

Lets bump the minor version also.:)

**Comment by pankajagrawal16** [comment]
Ok, let me have a look and will do a minor version bump

**Comment by pankajagrawal16** [comment]
@tsc-buddy Are you referring to this issue? https://github.com/Azure/bicep-registry-modules/issues/3316

**Comment by pankajagrawal16** [comment]
@tsc-buddy Updated the PR to support FlexConsumption. Have a look

**Comment by ReneHezser** [comment]
@pankajagrawal16 
We have added examples for Bicep parameter files to the Readme. This has been applied to all published modules but needs to be done for PRs as well. Can you please run the Set-AVMModule utility as detailed [here](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/generate-bicep-module-files/). It is required for the validation pipeline to succeed and the contribution to be published.

Please reach out if any support is needed.

**Review by tsc-buddy — APPROVED** [review]

**Pull request merged**
