### PR TITLE
fix: AppServicePlan - SKU selection improvements

### LINKED ISSUE #1506: [AVM Module Issue]: res/web/serverfarm - I need to specify tier in SKU I will otherwise get an error
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/web/serverfarm

### (Optional) Module Name if not listed above

_No response_

### (Optional) Module Version

_No response_

### Description

Related https://github.com/Azure/bicep-registry-modules/issues/1505

This is because AVM is WAF-aligned and the module checking the value for tier.
The less I need to overwrite, the better. Can we supply just name?

### (Optional) Correlation Id

_No response_

### PR DESCRIPTION
**Pull request by tsc-buddy**
## Description
Provides improvements to simplify the selection of SKUs for App Service Plans by relying on the RP to provide the values for 'tier', 'family' and 'size' properties based on the 'name' provided. Logic adjusted on ZR param to accommodate the change also.

Closes #1506 

## Pipeline Reference

| Pipeline |
| -------- |
|     [avm.res.web.serverfarm](https://github.com/tsc-buddy/bicep-registry-modules/actions/workflows/avm.res.web.serverfarm.yml)     |

## Type of Change

- [ ] Update to CI Environment or utlities (Non-module effecting changes)
- [x] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [x] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [x] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Comment by tsc-buddy** [comment]
@Azure/avm-core-team-technical-bicep - Can you provide some guidance on whether the change to the way the SKU parameter now works, warrants a bump in version or not? I was unsure, so didn't adjust it, but I'm mindful the way the SKU was provided has change from an object with 5 properties to, two separate spring params and others being handled by the RP. Technically breaking peoples current approach to the usage of the module, but not the provisioned resources.

**Comment by AlexanderSehr** [comment]
> > @Azure/avm-core-team-technical-bicep - Can you provide some guidance on whether the change to the way the SKU parameter now works, warrants a bump in version or not? I was unsure, so didn't adjust it, but I'm mindful the way the SKU was provided has change from an object with 5 properties to, two separate spring params and others being handled by the RP. Technically breaking peoples current approach to the usage of the module, but not the provisioned resources.
> 
> Just my 2 cents:
> 
> Since you are changing the "interface" to the module - including **new required** parameters - this should definitely be a new version.
> 
> The people who previously used the module in the current version do not set the "skuCapacity" parameter, for example. Their template will then become invalid, even if _they_ didn't change the module version..

100% correct @cloudchristoph. As we're still in the 'pre 1.0' phase, plese update the module's version to the next minor @tsc-buddy.

That being said and for context, @cloudchristoph, a change to a module always results in a new version / we never overwrite a current one. But we still want to adhere semver (especially from 1.0 onwards), so it remains a valid ask to explicitely bump up the version (to in this case at least a new minor).

**Review by AlexanderSehr — CHANGES_REQUESTED** [review]
Please bump the version in the `version.json` file as per the dicsussion in the PR's comments.

**Comment by tsc-buddy** [comment]
> Please bump the version in the `version.json` file as per the dicsussion in the PR's comments.

All done. Thanks @AlexanderSehr

**Review by AlexanderSehr — APPROVED** [review]

**Pull request merged**
