### PR TITLE
refactor: resolver module description fixes and added UDTs

### PR DESCRIPTION
**Pull request by johnlokerse**
## Description

In this pull request the following changes can be found:
- Updated descriptions to refer to the correct resource `Private DNS Resolver` to `DNS Private Resolver`
- Added user-defined types for inbound and outbound endpoints

## Updating an existing module

- [ ] This is a bug fix:
  - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
  - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
- [ ] I have run `brm validate` locally to verify the module files.
- [x] I have run deployment tests locally to ensure the module is deployable.
- [x] I have read the [Updating an existing module](https://github.com/Azure/bicep-registry-modules/blob/main/CONTRIBUTING.md#updating-an-existing-module) section in the contributing guide and updated the `version.json` file properly:
  - [ ] The PR contains backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`.
  - [x] The PR contains backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] The PR contains breaking changes, and I have bumped the MAJOR version in `version.json`.
- [x] I have updated the examples in README with the latest module version number.

Green pipeline/action:

[avm.res.network.dns-resolver](https://github.com/johnlokerse/bicep-registry-modules/actions/workflows/avm.res.network.dns-resolver.yml)

### CODE REVIEW

**Comment by johnlokerse** [comment]
I will run the GitHub action to test the changes later!

**Comment by AlexanderSehr** [comment]
Awesome, thanks @johnlokerse. @ChrisSidebotham, given that you're the owner, please also take a look ;)

**Comment by AlexanderSehr** [comment]
ping @ChrisSidebotham

**Review by AlexanderSehr — COMMENTED** [review]
Looks all good to me. @ChrisSidebotham ?

**Comment by johnlokerse** [comment]
@ChrisSidebotham Let me know if you there is something I can do 😃

**Review by ChrisSidebotham — APPROVED** [review]
Looks good to me @johnlokerse - Apologies for the delay in response

**Pull request merged**
