### PR TITLE
feat: Update `avm/res/document-db/database-account` module to support `table` entities

### LINKED ISSUE #1545: [Module Proposal]: `avm/res/document-db/database-account/table`
### Check for previous/existing GitHub issues/module proposals

- [x] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [x] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/document-db/database-account/table

### Module Details

Azure Cosmos DB for Table now supports Microsoft Entra authentication (https://learn.microsoft.com/azure/cosmos-db/table/security).

As part of this, I'm working on Azure Developer CLI quickstart template using AVM modules and I noticed that I'm unable to create an account for Table as the `capabilities` array requires the account to be either NoSQL, MongoDB, or Apache Gremlin.

I'm planning a pull request to add the ability to create a table within an Azure Cosmos DB account.

I'm going to base it on this implementation: (https://github.com/Azure-Samples/cosmos-db-table-dotnet-quickstart/blob/2069c418a2bd8a9b3565e0456a9037d9582d7ad7/infra/core/database/cosmos-db/table/table.bicep)

And I will add the best practices from your current sub-resource implementations.

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

seesharprun

### (Optional) Secondary Module Owner's GitHub Username (handle)

markjbrown

### PR DESCRIPTION
**Pull request by seesharprun**
## Description

> - Depends on #3565
> - Resolves Azure/Azure-Verified-Modules#1545

## Pipeline Reference

| Pipeline |
| -------- |
| [avm.res.document-db.database-account](https://github.com/seesharprun/bicep-registry-modules/actions/workflows/avm.res.document-db.database-account.yml) |

## Type of Change

- [ ] Update to CI Environment or utilities (Non-module affecting changes)
- [ ] Azure Verified Module updates:
  - [ ] Bugfix containing backwards-compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [x] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [x] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Comment by seesharprun** [comment]
I'm waiting to get access to grant my service prinicpal `User Access Administrator` to run the pipeline tests.

**Comment by seesharprun** [comment]
@bryansan-msft, this is not ready for review until I can resolve the downstream dependency (PR)

**Comment by seesharprun** [comment]
I'm going to temporarily close this PR and re-open later.

**Comment by seesharprun** [comment]
The prerequisite PR is now closed, so I can work on this now.

**Comment by bryansan-msft** [comment]
Let me know when is ready to review

**Comment by seesharprun** [comment]
> Let me know when is ready to review

I'm running the pipelines in my fork now. Once I get "all greens," I will mark this pull request as ready for review and ping you.

Thanks!

**Comment by seesharprun** [comment]
@bryansan-msft, all tests are green in my fork. You can review now.

**Review by ghost — APPROVED** [review]
LGTM. Does Table API support any sort of extra configuration like other apis? or is it just create the database and nothing else?

**Comment by AlexanderSehr** [comment]
Hey @bryansan-msft & @seesharprun, please not that, like with the previous PR - the module version was **not** published due to capacity issues in on of the tests. I'll re-run the failed jobs a few times in the hopes it will eventually work, but if not we may need to find a different solution (e.g., via a new PR that sets a different region for the 'multiRegion' test).

**Comment by seesharprun** [comment]
> Hey @bryansan-msft & @seesharprun, please not that, like with the previous PR - the module version was **not** published due to capacity issues in on of the tests. I'll re-run the failed jobs a few times in the hopes it will eventually work, but if not we may need to find a different solution (e.g., via a new PR that sets a different region for the 'multiRegion' test).

I'll open a new PR to try and work on this. I guessed in #3588, that it was an issue with the auto-calculated paired region, but I haven't looked into it yet. It's good to know that this is caused by the multi-region test.

**Comment by bryansan-msft** [comment]
This one closes #1640

**Pull request merged**
