### PR TITLE
Patch Release Update for lz-vending module

### PR DESCRIPTION
**Pull request by jtracey93**
## Description

As per https://github.com/Azure/bicep-lz-vending/pull/38 this is adding the release upstream to the registry for consistency.

## Updating an existing module

- [x] This is a bug fix:
  - [x] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
  - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
- [x] I have run `brm validate` locally to verify the module files.
- [x] I have run deployment tests locally to ensure the module is deployable. - see associated PR
- [x] I have read the [Updating an existing module](../CONTRIBUTING.md#updating-an-existing-module) section in the contributing guide and updated the `version.json` file properly:
  - [x] The PR contains backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`.
  - [ ] The PR contains backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] The PR contains breaking changes, and I have bumped the MAJOR version in `version.json`.

### CODE REVIEW

**Comment by jtracey93** [comment]
@shenglol please can we make an exception on the tests here please as this has passed our test framework fine as you can see on checks here: https://github.com/Azure/bicep-lz-vending/pull/38

Also as we have cut a release we want customers to have a consistent experience across consumption methods of this module.

Thanks

Jack

**Comment by shenglol** [comment]
Hmm I thought @dciborow added ARM-TTK as an optional step. Let me fix that quickly.

**Comment by dciborow** [comment]
@shenglol i see three items popping in ARM-TTK.

1. Microsoft.Authorization/roleAssignments uses a preview version ( 2020-10-01-preview ) and there are more recent versions available.
2. Type Mismatch: Parameter 'localVnetName' in nested template '[format('{0}-virtualNetworkPeering-remote-{1}', uniqueString(deployment().name, parameters('location')), copyIndex())]' is defined as string, but the parent template defines it as array).
3. Empty property:  ""

I actually think we should figure out why these errors are occurring in ARM-TTK before skipping it.

**Comment by shenglol** [comment]
@jtracey93 I've make ARM-TTK step optional. You may merge `main` to fix the error.

@dciborow We may need to add a bicepconfig.json to root and enable `use-recent-api-versions` to mitigate 1. For 2, maybe there are still gaps between the Bicep linter and ARM-TTK, but I think we shouldn't block PRs anyway, since the deployment test passed. Do you mind opening issues in the Bicep repo to track them?

**Comment by jtracey93** [comment]
@shenglol, thanks for sorting that so quickly. This is now good to review, approve and merge  👍

**Review by shenglol — APPROVED** [review]
:shipit:

**Pull request merged**
