### PR TITLE
fix: add new allowable values for licenseType - RHEL_BYOS / SLES_BYOS

### LINKED ISSUE #1676: [AVM Module Issue]: Unable to set licenseType to RHEL_BYOS for linux VMs
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/compute/virtual-machine

### (Optional) Module Version

0.2.3

### Description

For Linux VMs that use Bring Your Own Subscription, we can't set licenseType to "RHEL_BYOS" for these images because the input parameter only allows Windows values (Windows_Client / Windows_Server) or an empty string.

Need to add "RHEL_BYOS" as an allowed value.

### (Optional) Correlation Id

_No response_

### PR DESCRIPTION
**Pull request by oramoss**
## Description
This change adds two extra allowed values for the licenseType parameter in the virtual-machine AVM template.
The two new allowed parameter values are:

RHEL_BYOS
SLES_BYOS

Fixes #1676

## Pipeline Reference

| Pipeline |
| -------- |
|[avm.res.compute.virtual-machine](https://github.com/oramoss/bicep-registry-modules/actions/workflows/avm.res.compute.virtual-machine.yml)|

## Type of Change

- [ ] Update to CI Environment or utlities (Non-module effecting changes)
- [x] Azure Verified Module updates:
  - [x] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [x] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [x] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Review by eriqua — COMMENTED** [review]
Hey @oramoss, thanks for your contribution. Please be aware that we just merged a bigger update to the VM module. For this reason this PR shows conflicts. Could you please merge latest upstream back to your fork?

CC: @rahalan to follow up

**Comment by oramoss** [comment]
> @oramoss please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree [company="AzurePremium"]

**Comment by oramoss** [comment]
> @oramoss the command you issued was incorrect. Please try again.
> 
> Examples are:
> 
> ```
> @microsoft-github-policy-service agree
> ```
> 
> and
> 
> ```
> @microsoft-github-policy-service agree company="your company"
> ```

@microsoft-github-policy-service agree company="AzurePremium"

**Comment by oramoss** [comment]
> @microsoft-github-policy-service agree company="your company"

@microsoft-github-policy-service agree company="AzurePremium"

**Review by rahalan — APPROVED** [review]

**Pull request merged**
