### PR TITLE
fixed warning - game-dev-vm

### PR DESCRIPTION
**Pull request by vlahane**
## Description

If you haven't already, read the full [contribution guide](../CONTRIBUTING.md). The guide may have changed since the last time you read it, so please double-check. Once you are done and ready to submit your PR, edit the PR description and run through the relevant checklist below.

Enable GitHub Worksflows in your fork to enable auto-generation of assets with our [GitHub Action](/.github/workflows/push-auto-generate.yml).
To trigger GitHub Actions after auto-generation, [add a GitHub PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) as a secret in your forked repository called `PAT`.

## Adding a new module

- [ ] A proposal has been submitted and approved.
- [ ] I have included "Closes #{module_proposal_issue_number}" in the PR description.
- [ ] I have run `brm validate` locally to verify the module files.
- [ ] I have run deployment tests locally to ensure the module is deployable.

## Updating an existing module

- [ ] This is a bug fix:
  - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
  - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
- [x] I have run `brm validate` locally to verify the module files.
- [ ] I have run deployment tests locally to ensure the module is deployable.
- [ ] I have read the [Updating an existing module](../CONTRIBUTING.md#updating-an-existing-module) section in the contributing guide and updated the `version.json` file properly:
  - [ ] The PR contains backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`.
  - [ ] The PR contains backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] The PR contains breaking changes, and I have bumped the MAJOR version in `version.json`.

### CODE REVIEW

**Comment by alex-frankel** [comment]
@vlahane -- based on the CI errors, it looks like you are trying to update multiple top-level modules in this PR, which is not possible today. Can you stage this out into separate PRs? If there are cross references, these will need to be done serially, so you can pull in the latest version of the relevant module.

**Review by alex-frankel — DISMISSED** [review]
Please separate into separate PRs

**Comment by vlahane** [comment]
@alex-frankel  done, please check!
1) https://github.com/Azure/bicep-registry-modules/pull/269
2) https://github.com/Azure/bicep-registry-modules/pull/268

not sure why current PR failed with below error! 

`[31;1mNew-AzResourceGroupDeployment: [31;1m9:50:18 AM - Error: Code=MarketplacePurchaseEligibilityFailed; Message=Marketplace purchase eligibilty check returned errors. See inner errors for details. `

**Comment by dciborow** [comment]
> @alex-frankel done, please check!
> 
> 1. [fixed warning- virtual-network #269](https://github.com/Azure/bicep-registry-modules/pull/269)
> 2. [fixed warning- daprComponent-stor.bicep #268](https://github.com/Azure/bicep-registry-modules/pull/268)
> 
> not sure why current PR failed with below error!
> 
> `�[31;1mNew-AzResourceGroupDeployment: �[31;1m9:50:18 AM - Error: Code=MarketplacePurchaseEligibilityFailed; Message=Marketplace purchase eligibilty check returned errors. See inner errors for details. `

This is probably on me...

**Comment by dciborow** [comment]
This PR should fix the current issue. #271

**Review by dciborow — APPROVED** [review]

**Comment by shenglol** [comment]
image

The sub issue was resolved, but the deployment failed due to the error above. @vlahane @dciborow Any idea?

**Comment by vlahane** [comment]
> image
> 
> The sub issue was resolved, but the deployment failed due to the error above. @vlahane @dciborow Any idea?

 @shenglol  We should be good now, merge code from main

**Review by shenglol — APPROVED** [review]

**Pull request merged**
