### PR TITLE
fix: Update the module identifiers in the issue template to the correct alphabetical order.

### PR DESCRIPTION
**Pull request by Menghua1**
## Description
Fixes pipeline issue https://github.com/Azure/bicep-registry-modules/actions/runs/11288332565/job/31395906879.

## Pipeline Reference

| Pipeline |
| -------- |
|  [avm.ptn.azd.ml-project](https://github.com/Menghua1/bicep-registry-modules/actions/workflows/avm.ptn.azd.ml-project.yml)        |

## Type of Change

- [ ] Update to CI Environment or utilities (Non-module affecting changes)
- [x] Azure Verified Module updates:
  - [ ] Bugfix containing backwards-compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [ ] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings

@jongio for notification.

### CODE REVIEW

**Comment by Menghua1** [comment]
@AlexanderSehr Could you help review this PR?

**Comment by AlexanderSehr** [comment]
Hey @Menghua1,
you can close this PR. @eriqua already fixed the issue and the module got published [here](https://github.com/Azure/bicep-registry-modules/actions/runs/11289290695).

**Comment by eriqua** [comment]
Hey @Menghua1 thanks for this. Since the issue template bug was blocking other PR runs too (it's a global test) we had to fix that promptly. Sorry if I did not spot it in the review 🙁 

However I see you fixed the codeowners file as well, so we can anyway have the PR in 🙂

**Review by eriqua — APPROVED** [review]
🆗

**Pull request merged**
