### PR TITLE
feat: separate backup snapshot policies netapps

### PR DESCRIPTION
**Pull request by Salima-90**
## Description
- ANF backup and snapshot policies have been separated into their own modules

## Pipeline Reference

| Pipeline |
| -------- |
|         [avm.res.net-app.net-app-account](https://github.com/Salima-90/bicep-registry-modules/actions/workflows/avm.res.net-app.net-app-account.yml) |

## Type of Change

- [x] Update to CI Environment or utilities (Non-module affecting changes)
- [x] Azure Verified Module updates:
  - [ ] Bugfix containing backwards-compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [ ] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Comment by ReneHezser** [comment]
@Salima-90 
We have added examples for Bicep parameter files to the Readme. This has been applied to all published modules but needs to be done for PRs as well. Can you please run the Set-AVMModule utility as detailed [here](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/generate-bicep-module-files/). It is required for the validation pipeline to succeed and the contribution to be published.

Please reach out if any support is needed.

**Comment by Salima-90** [comment]
> @Salima-90 We have added examples for Bicep parameter files to the Readme. This has been applied to all published modules but needs to be done for PRs as well. Can you please update your branch and run the Set-AVMModule utility as detailed [here](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/generate-bicep-module-files/). It is required for the validation pipeline to succeed and the contribution to be published.
> 
> Please reach out if any support is needed.

Is there a command to be run? Or

> @Salima-90 We have added examples for Bicep parameter files to the Readme. This has been applied to all published modules but needs to be done for PRs as well. Can you please update your branch and run the Set-AVMModule utility as detailed [here](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/generate-bicep-module-files/). It is required for the validation pipeline to succeed and the contribution to be published.
> 
> Please reach out if any support is needed.

Does Bicep Parameter examples need to be added manually for backup policies and snapshot policies?

**Comment by ReneHezser** [comment]
> > @Salima-90 We have added examples for Bicep parameter files to the Readme. This has been applied to all published modules but needs to be done for PRs as well. Can you please update your branch and run the Set-AVMModule utility as detailed [here](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/generate-bicep-module-files/). It is required for the validation pipeline to succeed and the contribution to be published.
> > Please reach out if any support is needed.
> 
> Does Bicep Parameter examples need to be added manually for backup policies and snapshot policies?

Hi @Salima-90 you are fine, as the examples are only added to the top-level module.

**Comment by Salima-90** [comment]
> 

@microsoft-github-policy-service agree

**Comment by bobmclane999** [comment]
Hi @fbinotto hope you are well..!? this is Salima's PR to separate those Backup and Snapshot Policies out to their own files as per - https://github.com/Azure/bicep-registry-modules/pull/3055 is there any chance this can be approved please?
Thanks Shaun

**Review by fbinotto — APPROVED** [review]
LGTM

**Pull request merged**
