### PR TITLE
fix: Update publishing job to only trigger if git repo is assocaited to the upstream repo

### PR DESCRIPTION
**Pull request by oZakari**
## Description

Experiencing the publishing job getting triggered when using the main branch in forks. Adding an additional condition to the job to only trigger if the workflow is being run within the upstream repository.  

https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

## Pipeline Reference

Pipeline run with context set to my fork
https://github.com/oZakari/bicep-registry-modules/actions/runs/8930012279

Pipeline with context set to Azure org
https://github.com/oZakari/bicep-registry-modules/actions/runs/8930022963

## Type of Change

- [x] Update to CI Environment or utlities (Non-module effecting changes)
- [ ] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [ ] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [ ] I have run `Set-AVMModule` locally to generate the supporting module files.
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Comment by ChrisSidebotham** [comment]
Seems like a pretty solid idea to me! @AlexanderSehr / @eriqua  anything to add on this?

**Comment by AlexanderSehr** [comment]
> Seems like a pretty solid idea to me! @AlexanderSehr / @eriqua anything to add on this?

I guess it would do the trick for now. But I'll leave the ultimate choice to @eriqua as I know she's been working on the publishing to some extend as well.

**Comment by eriqua** [comment]
> > Seems like a pretty solid idea to me! @AlexanderSehr / @eriqua anything to add on this?
> 
> I guess it would do the trick for now, thanks @oZakari - it's much appreciated. 🚀 However, I'll leave the ultimate choice to @eriqua as I know she's been working on the publishing to some extend as well.

Thanks @oZakari for this improvement.
As part of the bigger publishing update, the same condition will probably be moved to the actual publishing to registry step instead, to be able to still test tag creation for example. Nevertheless, no reason to block this today from my side.

**Review by AlexanderSehr — APPROVED** [review]
Great, then we're all in agreement. Will approve & merge. Thanks @oZakari 🚀

**Pull request merged**
