### PR TITLE
fix: Databricks - Updated to latest PE schema - `avm/res/databricks/workspace`

### LINKED ISSUE #1943: Update the PE implementation of `avm/res/databricks/workspace`

### PR DESCRIPTION
**Pull request by AlexanderSehr**
## Description

- Updated PE implementation to latest schema
- Addressed Bicep warning

## Pipeline Reference

| Pipeline |
| -------- |
|     [avm.res.databricks.workspace](https://github.com/Azure/bicep-registry-modules/actions/workflows/avm.res.databricks.workspace.yml)    |

## Type of Change

- [ ] Update to CI Environment or utlities (Non-module effecting changes)
- [ ] Azure Verified Module updates:
  - [x] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [ ] Update to documentation

### CODE REVIEW

**Comment by ChrisSidebotham** [comment]
@clintgrove to review

**Comment by eriqua** [comment]
Hey @clintgrove please have a look when you get some time

**Comment by AlexanderSehr** [comment]
> @AlexanderSehr this surprisingly ended up having conflicts 😄 @clintgrove please have a look when you get some time We still have issues with RG removal (close to be fixed) but until then we should sync before merge, making sure the testing environment is cleaned up.

Conflicts resolved

**Review by clintgrove — COMMENTED** [review]
I have looked over the changes. They look ok. Are we having a discussion first, or can I go ahead and approve?

**Comment by AlexanderSehr** [comment]
> I have looked over the changes. They look ok. Are we having a discussion first, or can I go ahead and approve?

This is a change we've rolled out for most module quite some time ago. So, I hope there is nothing to discuss 😄 unless you want to have a word on the changes and why they were made

**Comment by AlexanderSehr** [comment]
Hey @clintgrove, can we go ahead with this one?

**Review by clintgrove — APPROVED** [review]
Good to go , thanks

**Pull request merged**
