### PR TITLE
fix: Set subnet batch size decorator

### LINKED ISSUE #1519: [AVM Module Issue]: avm/res/network/virtual-network duplicate subnet creations
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### Module Name

avm/res/network/virtual-network

### (Optional) Module Name if not listed above

_No response_

### (Optional) Module Version

0.1.5

### Description

I have used this module a few times and most of the times i don't have an issue with it and creating subnets. However, I have had to clone it and modify it locally for a particular project as I kept getting "Another operation on this or dependent resource is in progress" when creating the subnets (child module call).
I removed the child module call on the local version because (as the commented section in the bicep mentions) the subnets are already been done in the parent vnet resource.
I have seen the commented section and question is, is the child subnet module call suppose to be included in the module that is been referenced publicly or was that an oversight? In other words, is there a way you can test the subnet module without then having this duplicate call included in the public referenced module?
If it is to stay and therefore duplicate the subnet creation, can we have a batch decorator to help prevent these error messages?

PS: love using these module, great work to all the team helping to create and maintain them :)

### (Optional) Correlation Id

a8b70743-ceff-41e0-933e-0bdd2c1a05be

### PR DESCRIPTION
**Pull request by rodney-almeida**
## Description
Rerunning the vnet module with multiple subnets over an existing vnet resource can at times cause a 'another operation is in progress' error. For this reason the batchSize decorator has been added for the subsequent subnet child module call to minimise this error.

## Pipeline Reference

| Pipeline |
| -------- |
|     [avm.res.network.virtual-network](https://github.com/rodney-almeida/bicep-registry-modules/actions/workflows/avm.res.network.virtual-network.yml)     |

## Type of Change

- [ ] Update to CI Environment or utlities (Non-module effecting changes)
- [x] Azure Verified Module updates:
  - [x] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`:
    - [x] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `version.json`.
  - [x] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] I have run `Set-AVMModule` locally to generate the supporting module files.
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings

### CODE REVIEW

**Comment by rodney-almeida** [comment]
@microsoft-github-policy-service agree

**Comment by rodney-almeida** [comment]
@elbatane Is there anything missing from my side that is blocking this from being approved?
Thanks

**Comment by AlexanderSehr** [comment]
> @elbatane Is there anything missing from my side that is blocking this from being approved? Thanks

Looks good to me. @elbatane, let me know if I can help 💪 
And of course thanks for the PR @rodney-almeida. 🚀

**Review by elbatane — DISMISSED** [review]

**Comment by rodney-almeida** [comment]
@AlexanderSehr, not sure what the assignment to me is for? Looks like it is approved. Just needs to be merged?!?!

**Comment by elbatane** [comment]
@rodney-almeida could you please pull the latest changes from main and solve the conflict? Thank you very much!

**Comment by rodney-almeida** [comment]
@elbatane, i resolved the merge conflict. Please confirm if ok. If so, please approve AND merge.

**Comment by AlexanderSehr** [comment]
> @AlexanderSehr, not sure what the assignment to me is for? Looks like it is approved. Just needs to be merged?!?!

Just assigned it to as you've been working on the PR :)

**Review by elbatane — APPROVED** [review]

**Pull request merged**
