### PR TITLE
Update README.md - remove orphan message

### PR DESCRIPTION
**Pull request by clintgrove**
## Description

Taking out the orphan module message as I am now the owner

## Adding a new module

- [ ] A proposal has been submitted and approved.
- [ ] I have included "Closes #{module_proposal_issue_number}" in the PR description.
- [ ] I have run `brm validate` locally to verify the module files.
- [ ] I have run deployment tests locally to ensure the module is deployable.

## Updating an existing module

- [ ] This is a bug fix:
  - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
  - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
- [ ] I have run `brm validate` locally to verify the module files.
- [ ] I have run deployment tests locally to ensure the module is deployable.
- [ ] I have read the [Updating an existing module](https://github.com/Azure/bicep-registry-modules/blob/main/CONTRIBUTING.md#updating-an-existing-module) section in the contributing guide and updated the `version.json` file properly:
  - [ ] The PR contains backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `version.json`.
  - [ ] The PR contains backwards compatible feature updates, and I have bumped the MINOR version in `version.json`.
  - [ ] The PR contains breaking changes, and I have bumped the MAJOR version in `version.json`.
- [ ] I have updated the examples in README with the latest module version number.

### CODE REVIEW

**Comment by ChrisSidebotham** [comment]
@clintgrove - Please remove the Orphaned.md file and then rerun the readme utility descibed here https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/generate-bicep-module-files/

**Comment by eriqua** [comment]
> @clintgrove - Please remove the Orphaned.md file and then rerun the readme utility descibed here https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/generate-bicep-module-files/

Also @ChrisSidebotham @clintgrove I see the csv is not yet showing ownership for this module, so we need to wait for that before merging the change :)

Welcome @clintgrove btw and thanks for owning this module!

**Review by AlexanderSehr — CHANGES_REQUESTED** [review]
Thanks for your contribution. 💪Please note, the file also must be removed from the module folder

**Comment by AlexanderSehr** [comment]
> > @clintgrove - Please remove the Orphaned.md file and then rerun the readme utility descibed here https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/generate-bicep-module-files/
> 
> Also @ChrisSidebotham @clintgrove I see the csv is not yet showing ownership for this module, so we need to wait for that before merging the change :)
> 
> Welcome @clintgrove btw and thanks for owning this module!

cc: @matebarabas

**Comment by clintgrove** [comment]
Closing this as generated in feature

**Pull request closed without merging**
